# fly.toml app configuration file generated for bytewise-nutritionist
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "bytewise-nutritionist"
primary_region = "iad"

[build]

[deploy]
  release_command = "npm run db:push"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[machines]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Static files are served by Express server from server/public
# Express handles SPA fallback routing for deep links