github.com:
    users:
        stephenB75:
            oauth_token: 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
    git_protocol: https
    user: stephenB75
    oauth_token: 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
