import type { FastFoodCategory, FastFoodItem } from './fastFoodMenu';

/**
 * Brunch / tapas chains that were missing from Places.
 * Another Broken Egg Cafe — published nutrition PDF (sandwich/omelette/benedict figures).
 * Snooze an AM Eatery — January 2026 nutritional information PDF.
 * The Melting Pot — published menu calories + FatSecret macros (sodium ≈ typical when omitted).
 * Santiago's Bodega — no official nutrition guide; calories/macros estimated from typical tapas portions (Atwater-aligned).
 */
const item = (
  id: string,
  name: string,
  restaurant: string,
  category: FastFoodCategory,
  serving: string,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  sodium: number,
  keywords?: string[],
): FastFoodItem => ({ id, name, restaurant, category, serving, calories, protein, carbs, fat, sodium, ...(keywords ? { keywords } : {}) });

export const BRUNCH_TAPAS_FAST_FOOD_ITEMS: FastFoodItem[] = [
  // ——— Another Broken Egg Cafe ———
  item('abe-eggs-benedict', 'Eggs Benedict (benedict only)', 'Another Broken Egg Cafe', 'breakfast', '1 order', 590, 40, 32, 22, 2300, ['benedict', 'brunch']),
  item('abe-blackstone', 'Eggs Blackstone Benedict (benedict only)', 'Another Broken Egg Cafe', 'breakfast', '1 order', 810, 37, 37, 50, 1430, ['benedict']),
  item('abe-crab-benny', 'Crab Cake Benedict (benedict only)', 'Another Broken Egg Cafe', 'breakfast', '1 order', 800, 42, 42, 39, 1750, ['benedict', 'crab']),
  item('abe-salmon-benny', 'Smoked Salmon Benedict (benedict only)', 'Another Broken Egg Cafe', 'breakfast', '1 order', 640, 40, 41, 21, 1720, ['benedict', 'salmon']),
  item('abe-bacon-tomato-benny', 'Bacon & Grilled Tomato Benedict (benedict only)', 'Another Broken Egg Cafe', 'breakfast', '1 order', 810, 37, 37, 50, 1430, ['benedict', 'bacon']),
  item('abe-chicken-biscuit', 'Broken Egg Chicken & Biscuit (sandwich only)', 'Another Broken Egg Cafe', 'breakfast', '1 sandwich', 850, 41, 57, 50, 2070, ['biscuit', 'chicken']),
  item('abe-chicken-biscuit-plate', 'Broken Egg Chicken & Biscuit with Potatoes', 'Another Broken Egg Cafe', 'breakfast', '1 plate', 1170, 42, 70, 65, 2230, ['biscuit', 'chicken']),
  item('abe-biscuit-gravy-eggs', 'Biscuit & Gravy with Two Scrambled Eggs', 'Another Broken Egg Cafe', 'breakfast', '1 plate', 1050, 46, 64, 71, 3020, ['biscuit', 'gravy']),
  item('abe-day-starter-bacon', 'Traditional Day Starter (fried eggs, bacon, English muffin)', 'Another Broken Egg Cafe', 'breakfast', '1 plate', 540, 28, 29, 28, 910, ['eggs', 'bacon']),
  item('abe-sunrise-spinach', 'Sunrise Spinach Scrambler (scrambler only)', 'Another Broken Egg Cafe', 'breakfast', '1 scrambler', 600, 39, 6, 51, 920, ['scrambler', 'spinach']),
  item('abe-chorizo-avocado', 'Chorizo & Avocado Omelette (omelette only)', 'Another Broken Egg Cafe', 'breakfast', '1 omelette', 760, 41, 15, 65, 1230, ['omelette', 'chorizo']),
  item('abe-bacquezo', 'Bacquezo Omelette (omelette only)', 'Another Broken Egg Cafe', 'breakfast', '1 omelette', 1000, 50, 7, 84, 1550, ['omelette', 'bacon']),
  item('abe-floridian', 'The Floridian Omelette (omelette only)', 'Another Broken Egg Cafe', 'breakfast', '1 omelette', 700, 42, 4, 58, 890, ['omelette']),
  item('abe-southwest-scrambler', 'Southwest Scrambler with Guacamole & Salsa', 'Another Broken Egg Cafe', 'breakfast', '1 scrambler', 710, 40, 16, 59, 1250, ['scrambler']),
  item('abe-huevos', 'Huevos Rancheros', 'Another Broken Egg Cafe', 'breakfast', '1 plate', 960, 32, 56, 63, 1580, ['huevos']),
  item('abe-chicken-waffles', 'Chicken & Waffles', 'Another Broken Egg Cafe', 'breakfast', '1 plate', 670, 49, 54, 31, 1630, ['waffle', 'chicken']),
  item('abe-shrimp-grits', "Shrimp 'N Grits", 'Another Broken Egg Cafe', 'breakfast', '1 plate', 980, 37, 59, 72, 2630, ['shrimp', 'grits']),
  item('abe-classic-french-toast', 'Classic French Toast', 'Another Broken Egg Cafe', 'breakfast', '1 order', 940, 32, 114, 44, 1320, ['french toast']),
  item('abe-belgian-waffle', 'Belgian Waffle', 'Another Broken Egg Cafe', 'breakfast', '1 waffle', 280, 6, 46, 10, 630, ['waffle']),
  item('abe-buttermilk-pancakes', 'Buttermilk Pancakes', 'Another Broken Egg Cafe', 'breakfast', '1 stack', 480, 17, 95, 6, 1520, ['pancakes']),
  item('abe-benedict-burger', 'Benedict Burger with Potatoes', 'Another Broken Egg Cafe', 'sandwiches', '1 burger + side', 1240, 50, 82, 85, 5830, ['burger']),
  item('abe-bacon-burger', 'Classic Bacon Burger with Potatoes', 'Another Broken Egg Cafe', 'sandwiches', '1 burger + side', 1360, 68, 92, 84, 5330, ['burger', 'bacon']),
  item('abe-sonoma-club', 'Sonoma Club with Potatoes', 'Another Broken Egg Cafe', 'sandwiches', '1 sandwich + side', 1270, 57, 112, 73, 3390, ['club']),
  item('abe-southern-chicken', 'Southern Chicken Sandwich (fried) with Potatoes', 'Another Broken Egg Cafe', 'sandwiches', '1 sandwich + side', 1360, 70, 90, 82, 2590, ['chicken']),
  item('abe-southwest-chop', 'Southwest Chop Salad with Turkey', 'Another Broken Egg Cafe', 'lunch', '1 salad', 920, 37, 42, 72, 1790, ['salad']),
  item('abe-fried-chicken-salad', 'Southern Fried Chicken Salad', 'Another Broken Egg Cafe', 'lunch', '1 salad', 1130, 51, 47, 64, 1876, ['salad', 'chicken']),
  item('abe-country-potatoes', 'Fresh Country Potatoes', 'Another Broken Egg Cafe', 'snacks', '1 side', 320, 5, 23, 2, 260, ['side', 'potatoes']),
  item('abe-grits', 'Grits', 'Another Broken Egg Cafe', 'snacks', '1 side', 180, 3, 29, 5, 560, ['side', 'grits']),
  item('abe-city-grits', 'City Grits (bacon Gouda)', 'Another Broken Egg Cafe', 'snacks', '1 side', 460, 11, 12, 41, 850, ['side', 'grits']),

  // ——— Snooze an AM Eatery (Jan 2026 nutrition PDF) ———
  item('snooze-classic-high', 'The Snooze Classic (3-egg, higher-cal build)', 'Snooze an AM Eatery', 'breakfast', '1 plate', 1220, 44, 85, 77, 2810, ['eggs', 'brunch']),
  item('snooze-classic-low', 'The Snooze Classic (3-egg, lower-cal build)', 'Snooze an AM Eatery', 'breakfast', '1 plate', 790, 39, 49, 49, 1690, ['eggs', 'brunch']),
  item('snooze-denver', 'Denver Omelet', 'Snooze an AM Eatery', 'breakfast', '1 omelet', 860, 43, 50, 54, 2420, ['omelet']),
  item('snooze-protein-trio', 'Protein Trio Omelet', 'Snooze an AM Eatery', 'breakfast', '1 omelet', 980, 52, 45, 67, 2470, ['omelet']),
  item('snooze-garden', 'Garden Harvest Omelet', 'Snooze an AM Eatery', 'breakfast', '1 omelet', 700, 28, 15, 59, 1170, ['omelet', 'veggie']),
  item('snooze-ham-benny', 'Ham Benedict III', 'Snooze an AM Eatery', 'breakfast', '1 order', 1090, 34, 73, 74, 2470, ['benedict']),
  item('snooze-avo-benny', 'Smashed Avocado Benny', 'Snooze an AM Eatery', 'breakfast', '1 order', 1070, 27, 41, 79, 2560, ['benedict', 'avocado']),
  item('snooze-bravocado', 'Bravocado Toast', 'Snooze an AM Eatery', 'breakfast', '1 order', 820, 22, 65, 52, 1880, ['toast', 'avocado']),
  item('snooze-sweet-potato', 'Sweet Potato Veggie Smash Up', 'Snooze an AM Eatery', 'breakfast', '1 plate', 410, 11, 50, 20, 390, ['veggie']),
  item('snooze-egg-white', 'Protein & Veggie Egg White Scramble', 'Snooze an AM Eatery', 'breakfast', '1 plate', 390, 39, 13, 20, 1560, ['scramble']),
  item('snooze-burrito', 'Snooze Breakfast Burrito (green chile)', 'Snooze an AM Eatery', 'breakfast', '1 burrito', 1230, 49, 121, 62, 3530, ['burrito']),
  item('snooze-tacos-flour', "Juan's Breakfast Tacos (flour tortillas)", 'Snooze an AM Eatery', 'breakfast', '1 order', 1470, 38, 97, 73, 3050, ['tacos']),
  item('snooze-pancake-flight', 'Pancake Flight', 'Snooze an AM Eatery', 'breakfast', '1 flight', 850, 14, 119, 38, 950, ['pancakes']),
  item('snooze-sweet-potato-pancakes', 'Sweet Potato Pancakes', 'Snooze an AM Eatery', 'breakfast', '1 stack', 1230, 17, 202, 44, 1740, ['pancakes']),
  item('snooze-pineapple-pancakes', 'Pineapple Upside Down Pancakes', 'Snooze an AM Eatery', 'breakfast', '1 stack', 830, 19, 127, 30, 1010, ['pancakes']),
  item('snooze-blueberry-pancakes', 'Blueberry Pancakes', 'Snooze an AM Eatery', 'breakfast', '1 stack', 730, 16, 128, 20, 970, ['pancakes']),
  item('snooze-chocolate-chip-pancakes', 'Chocolate Chip Pancakes', 'Snooze an AM Eatery', 'breakfast', '1 stack', 970, 19, 158, 35, 970, ['pancakes']),
  item('snooze-french-toast-neat', 'French Toast Neat', 'Snooze an AM Eatery', 'breakfast', '1 order', 820, 17, 114, 35, 770, ['french toast']),
  item('snooze-omg-french-toast', 'OMG! French Toast', 'Snooze an AM Eatery', 'breakfast', '1 order', 950, 20, 112, 49, 970, ['french toast']),
  item('snooze-shrimp-grits', 'Shrimp & Grits', 'Snooze an AM Eatery', 'breakfast', '1 plate', 890, 27, 35, 66, 1540, ['shrimp', 'grits']),
  item('snooze-pork-belly-rice', 'Habanero Pork Belly Breakfast Fried Rice', 'Snooze an AM Eatery', 'breakfast', '1 plate', 930, 52, 66, 55, 3960, ['fried rice']),
  item('snooze-bacon', 'Snooze Signature Bacon', 'Snooze an AM Eatery', 'snacks', '1 side', 270, 16, 0, 22, 790, ['bacon']),
  item('snooze-hash-browns', 'Hash Browns', 'Snooze an AM Eatery', 'snacks', '1 side', 240, 3, 33, 11, 890, ['side']),

  // ——— The Melting Pot (per-person / ½-order figures) ———
  item('mp-cheddar-fondue', 'Wisconsin Cheddar Cheese Fondue (per person)', 'The Melting Pot', 'dinner', '1 serving', 347, 17, 7, 21, 980, ['fondue', 'cheese']),
  item('mp-alpine-fondue', 'Classic Alpine Cheese Fondue (per person)', 'The Melting Pot', 'dinner', '1 serving', 368, 23, 9, 25, 920, ['fondue', 'cheese']),
  item('mp-spinach-fondue', 'Spinach Artichoke Cheese Fondue (per person)', 'The Melting Pot', 'dinner', '1 serving', 302, 20, 29, 23, 1100, ['fondue', 'cheese']),
  item('mp-fiesta-fondue', 'Fiesta Cheese Fondue (per person)', 'The Melting Pot', 'dinner', '1 serving', 332, 17, 9, 21, 1050, ['fondue', 'cheese']),
  item('mp-quattro-fondue', 'Quattro Formaggio Cheese Fondue (per person)', 'The Melting Pot', 'dinner', '1 serving', 374, 22, 10, 26, 980, ['fondue', 'cheese']),
  item('mp-green-goddess', 'Green Goddess Cheddar Fondue (per person)', 'The Melting Pot', 'dinner', '1 serving', 428, 18, 8, 28, 1120, ['fondue', 'cheese']),
  item('mp-cheese-dippers', 'Cheese Fondue Dippers (bread, fruit, veggies)', 'The Melting Pot', 'snacks', '1 serving', 549, 12, 78, 18, 720, ['fondue', 'bread']),
  item('mp-cheddar-meal', 'Wisconsin Cheddar Fondue + Dippers (per person)', 'The Melting Pot', 'dinner', '1 course', 896, 29, 85, 39, 1700, ['fondue', 'meal']),
  item('mp-chicken-mojo', 'Breast of Chicken – Mojo (entrée protein)', 'The Melting Pot', 'dinner', '1 serving', 250, 52, 0, 3, 620, ['chicken', 'fondue']),
  item('mp-land-sea', 'Land & Sea / Coq au Vin style entrée (per person)', 'The Melting Pot', 'dinner', '1 serving', 360, 60, 2, 11, 980, ['fondue', 'entrée']),
  item('mp-house-salad', 'Melting Pot House Salad', 'The Melting Pot', 'lunch', '1 salad', 250, 6, 18, 16, 480, ['salad']),
  item('mp-caesar', 'Caesar Salad', 'The Melting Pot', 'lunch', '1 salad', 133, 5, 8, 10, 420, ['salad']),
  item('mp-california', 'California Salad', 'The Melting Pot', 'lunch', '1 salad', 168, 6, 6, 13, 280, ['salad']),
  item('mp-strawberry', 'Strawberry Almond Salad', 'The Melting Pot', 'lunch', '1 salad', 210, 6, 14, 14, 320, ['salad']),
  item('mp-smores-chocolate', "S'mores Chocolate Fondue (½ order)", 'The Melting Pot', 'snacks', '1/2 order', 371, 5, 41, 19, 180, ['fondue', 'chocolate', 'dessert']),
  item('mp-yin-yang', 'Yin & Yang Chocolate Fondue (½ order)', 'The Melting Pot', 'snacks', '1/2 order', 314, 3, 33, 19, 120, ['fondue', 'chocolate', 'dessert']),
  item('mp-flaming-turtle', 'Flaming Turtle Chocolate Fondue (½ order)', 'The Melting Pot', 'snacks', '1/2 order', 705, 8, 90, 33, 280, ['fondue', 'chocolate', 'dessert']),
  item('mp-dessert-plate', 'Dessert Plate for Chocolate Fondue (½ order)', 'The Melting Pot', 'snacks', '1/2 order', 341, 4, 50, 14, 160, ['dessert', 'fondue']),

  // ——— Santiago's Bodega (estimates — no official nutrition PDF) ———
  item('sb-french-onion', 'French Onion Soup (bowl)', "Santiago's Bodega", 'lunch', '1 bowl', 420, 22, 32, 22, 1180, ['soup', 'tapas', 'estimated']),
  item('sb-shrimp-bisque', 'Shrimp Bisque (bowl)', "Santiago's Bodega", 'lunch', '1 bowl', 380, 18, 22, 24, 980, ['soup', 'shrimp', 'estimated']),
  item('sb-avocado-pear', 'Avocado & Pear Salad', "Santiago's Bodega", 'lunch', '1 salad', 480, 10, 28, 38, 620, ['salad', 'tapas', 'estimated']),
  item('sb-greek', 'Greek Salad', "Santiago's Bodega", 'lunch', '1 salad', 390, 14, 18, 30, 880, ['salad', 'estimated']),
  item('sb-wedge', 'Wedge Salad', "Santiago's Bodega", 'lunch', '1 salad', 450, 12, 12, 40, 920, ['salad', 'estimated']),
  item('sb-tuna-ceviche', 'Yellowfin Tuna Ceviche', "Santiago's Bodega", 'snacks', '1 tapa', 220, 28, 8, 8, 540, ['ceviche', 'tapas', 'estimated']),
  item('sb-beef-carpaccio', 'Beef Carpaccio', "Santiago's Bodega", 'snacks', '1 tapa', 280, 24, 4, 18, 480, ['carpaccio', 'tapas', 'estimated']),
  item('sb-short-ribs', 'Beef Short Ribs (cherry-hoisin)', "Santiago's Bodega", 'dinner', '1 tapa', 520, 32, 28, 30, 980, ['ribs', 'tapas', 'estimated']),
  item('sb-brussels', 'Roasted Brussels Sprouts', "Santiago's Bodega", 'snacks', '1 tapa', 260, 8, 22, 16, 520, ['brussels', 'tapas', 'estimated']),
  item('sb-patatas', 'Patatas Bravas', "Santiago's Bodega", 'snacks', '1 tapa', 380, 6, 42, 20, 720, ['potatoes', 'tapas', 'estimated']),
  item('sb-croquettas', 'Croquettas', "Santiago's Bodega", 'snacks', '1 tapa', 420, 14, 28, 26, 780, ['tapas', 'estimated']),
  item('sb-chicken-skewers', 'Chicken Skewers', "Santiago's Bodega", 'dinner', '1 tapa', 340, 36, 8, 18, 680, ['chicken', 'tapas', 'estimated']),
  item('sb-shrimp-chorizo', 'Shrimp & Chorizo', "Santiago's Bodega", 'dinner', '1 tapa', 360, 28, 6, 24, 920, ['shrimp', 'tapas', 'estimated']),
  item('sb-gaucho', 'Gaucho Steak (skirt, chimichurri)', "Santiago's Bodega", 'dinner', '5 oz', 420, 38, 2, 28, 620, ['steak', 'tapas', 'estimated']),
  item('sb-shrimp-grits', 'Shrimp & Grits', "Santiago's Bodega", 'dinner', '1 tapa', 480, 28, 32, 26, 980, ['shrimp', 'grits', 'estimated']),
  item('sb-mini-quesadillas', 'Miniature Quesadillas', "Santiago's Bodega", 'snacks', '1 tapa', 390, 16, 28, 22, 780, ['quesadilla', 'tapas', 'estimated']),
  item('sb-cheese-board', 'Cheese Board', "Santiago's Bodega", 'snacks', '1 plate', 560, 24, 18, 42, 920, ['cheese', 'tapas', 'estimated']),
  item('sb-chocolate-pudding', 'Chocolate Bread Pudding', "Santiago's Bodega", 'snacks', '1 dessert', 520, 8, 62, 26, 380, ['dessert', 'estimated']),
];
