import type { FastFoodCategory, FastFoodItem } from './fastFoodMenu';

/**
 * Central Florida locals + chains still missing from Places.
 * World of Beer — Nov 2024 menu nutrition book (published).
 * BENTO Asian Kitchen + Sushi — Mar 2024 nutrition PDF (composed builds noted).
 * Linda's La Cantina, Beefy King, Mecatos, Bakery 1908, Summer Palace,
 * Gator's Dockside, Se7en Bites — no official PDFs; Atwater-aligned estimates
 * from USDA steak/sandwich analogs, typical Colombian/Chinese bakery figures,
 * and sports-bar / Southern brunch norms. Marked with estimated keyword where applicable.
 */
const item = (
  id: string,
  name: string,
  restaurant: string,
  category: FastFoodCategory,
  serving: string,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  sodium: number,
  keywords?: string[],
): FastFoodItem => ({ id, name, restaurant, category, serving, calories, protein, carbs, fat, sodium, ...(keywords ? { keywords } : {}) });

export const FLORIDA_LOCALS_FAST_FOOD_ITEMS: FastFoodItem[] = [
  // ——— Linda's La Cantina (Orlando steakhouse; USDA / steakhouse analogs) ———
  item('llc-filet-small', 'Small Filet Mignon', "Linda's La Cantina", 'dinner', '≈6 oz', 360, 42, 1, 20, 480, ['steak', 'filet', 'estimated']),
  item('llc-filet-med', 'Medium Filet Mignon', "Linda's La Cantina", 'dinner', '≈8 oz', 480, 56, 1, 27, 620, ['steak', 'filet', 'estimated']),
  item('llc-filet-large', 'Large Filet Mignon', "Linda's La Cantina", 'dinner', '≈10 oz', 600, 70, 2, 34, 780, ['steak', 'filet', 'estimated']),
  item('llc-ny-strip', 'New York Strip Steak', "Linda's La Cantina", 'dinner', '≈12 oz', 720, 68, 2, 48, 720, ['steak', 'strip', 'estimated']),
  item('llc-ribeye', 'Ribeye Steak', "Linda's La Cantina", 'dinner', '≈14 oz', 980, 74, 2, 74, 860, ['steak', 'ribeye', 'estimated']),
  item('llc-sirloin-8', 'Top Sirloin Strip (8 oz)', "Linda's La Cantina", 'dinner', '8 oz', 380, 48, 1, 20, 540, ['steak', 'sirloin', 'estimated']),
  item('llc-sirloin-12', 'Top Sirloin Strip (12 oz)', "Linda's La Cantina", 'dinner', '12 oz', 570, 72, 2, 30, 780, ['steak', 'sirloin', 'estimated']),
  item('llc-tbone', 'La Cantina T-Bone', "Linda's La Cantina", 'dinner', '≈16 oz', 860, 82, 2, 56, 820, ['steak', 'estimated']),
  item('llc-surf-turf', 'Surf & Turf (filet + shrimp)', "Linda's La Cantina", 'dinner', '1 entrée', 720, 68, 8, 42, 1420, ['steak', 'shrimp', 'estimated']),
  item('llc-snapper', 'Blackened Snapper', "Linda's La Cantina", 'dinner', '≈12 oz', 480, 52, 4, 26, 980, ['fish', 'snapper', 'estimated']),
  item('llc-french-onion', 'Baked French Onion Soup', "Linda's La Cantina", 'lunch', '1 bowl', 380, 14, 28, 22, 1180, ['soup', 'estimated']),
  item('llc-house-salad', 'House Salad', "Linda's La Cantina", 'lunch', '1 salad', 220, 6, 14, 16, 420, ['salad', 'estimated']),
  item('llc-fried-mushrooms', 'Fried Mushrooms', "Linda's La Cantina", 'snacks', '1 order', 520, 10, 48, 32, 980, ['appetizer', 'estimated']),
  item('llc-onion-rings', 'Onion Rings', "Linda's La Cantina", 'snacks', '1 order', 580, 8, 62, 32, 1120, ['appetizer', 'estimated']),
  item('llc-baked-potato', 'Baked Potato with Butter', "Linda's La Cantina", 'snacks', '1 potato', 320, 7, 58, 8, 280, ['side', 'estimated']),
  item('llc-cheeseburger', 'Bacon Cheeseburger', "Linda's La Cantina", 'sandwiches', '1 burger', 820, 42, 48, 52, 1480, ['burger', 'estimated']),

  // ——— Mecatos Bakery & Cafe (Colombian; typical bakery macros) ———
  item('mec-pan-de-bono', 'Pan de Bono (plain)', 'Mecatos Bakery & Cafe', 'snacks', '1 piece', 280, 10, 28, 14, 420, ['colombian', 'cheese bread', 'estimated']),
  item('mec-pan-guava', 'Guava Pan de Bono', 'Mecatos Bakery & Cafe', 'snacks', '1 piece', 310, 9, 36, 14, 400, ['colombian', 'guava', 'estimated']),
  item('mec-pan-nutella', 'Nutella Pan de Bono', 'Mecatos Bakery & Cafe', 'snacks', '1 piece', 360, 9, 38, 18, 380, ['colombian', 'estimated']),
  item('mec-bunuelo', 'Buñuelo', 'Mecatos Bakery & Cafe', 'snacks', '1 piece', 240, 8, 22, 14, 380, ['colombian', 'estimated']),
  item('mec-empanada-beef', 'Beef Empanada', 'Mecatos Bakery & Cafe', 'snacks', '1 empanada', 320, 12, 28, 18, 480, ['colombian', 'empanada', 'estimated']),
  item('mec-empanada-chicken', 'Chicken Empanada', 'Mecatos Bakery & Cafe', 'snacks', '1 empanada', 300, 13, 28, 16, 460, ['colombian', 'empanada', 'estimated']),
  item('mec-arepa-rellena', 'Stuffed Arepa (beef & cheese)', 'Mecatos Bakery & Cafe', 'lunch', '1 arepa', 520, 28, 42, 26, 880, ['colombian', 'arepa', 'estimated']),
  item('mec-quesito', 'Guava Cream Cheese Quesito', 'Mecatos Bakery & Cafe', 'snacks', '1 pastry', 280, 5, 32, 14, 220, ['colombian', 'pastry', 'estimated']),
  item('mec-pastel-pollo', 'Pastel de Pollo', 'Mecatos Bakery & Cafe', 'snacks', '1 pastry', 380, 14, 34, 20, 620, ['colombian', 'estimated']),
  item('mec-breakfast-croissant', 'Breakfast Croissant (egg, cheese, bacon)', 'Mecatos Bakery & Cafe', 'breakfast', '1 sandwich', 520, 22, 38, 30, 980, ['colombian', 'croissant', 'estimated']),
  item('mec-mallorca', 'Mallorca Sandwich', 'Mecatos Bakery & Cafe', 'sandwiches', '1 sandwich', 560, 24, 48, 28, 1120, ['colombian', 'estimated']),
  item('mec-avocado-toast', 'Avocado Toast', 'Mecatos Bakery & Cafe', 'breakfast', '1 order', 380, 10, 36, 22, 520, ['estimated']),
  item('mec-tres-leches', 'Tres Leches Cake (slice)', 'Mecatos Bakery & Cafe', 'snacks', '1 slice', 420, 8, 52, 20, 280, ['dessert', 'colombian', 'estimated']),
  item('mec-coffee', 'Colombian Coffee (medium)', 'Mecatos Bakery & Cafe', 'breakfast', 'medium', 5, 0, 1, 0, 5, ['coffee']),

  // ——— Bakery 1908 (Asian bakery; Chinese bakery analogs) ———
  item('b1908-pineapple', 'Pineapple Bun', 'Bakery 1908', 'snacks', '1 bun', 340, 6, 44, 16, 320, ['chinese bakery', 'estimated']),
  item('b1908-bbq-pork', 'BBQ Pork Bun (baked)', 'Bakery 1908', 'snacks', '1 bun', 290, 9, 40, 10, 480, ['chinese bakery', 'char siu', 'estimated']),
  item('b1908-taro', 'Taro Bun', 'Bakery 1908', 'snacks', '1 bun', 320, 5, 48, 12, 280, ['chinese bakery', 'estimated']),
  item('b1908-ham-cheese', 'Ham & Cheese Bun', 'Bakery 1908', 'snacks', '1 bun', 360, 12, 40, 16, 720, ['chinese bakery', 'estimated']),
  item('b1908-floss', 'Pork Floss Bun', 'Bakery 1908', 'snacks', '1 bun', 350, 10, 42, 14, 620, ['chinese bakery', 'estimated']),
  item('b1908-cream-cheese', 'Sweet Cream Cheese Bun', 'Bakery 1908', 'snacks', '1 bun', 330, 7, 42, 14, 360, ['chinese bakery', 'estimated']),
  item('b1908-egg-sandwich', 'Egg Sandwich Bun', 'Bakery 1908', 'breakfast', '1 bun', 380, 14, 38, 18, 680, ['chinese bakery', 'estimated']),
  item('b1908-soup-dumpling', 'Soup Dumplings (6)', 'Bakery 1908', 'snacks', '6 pieces', 360, 18, 42, 12, 980, ['dim sum', 'estimated']),
  item('b1908-pan-fried-dumpling', 'Pan Fried Pork Dumplings (5)', 'Bakery 1908', 'snacks', '5 pieces', 420, 16, 38, 22, 1120, ['dim sum', 'estimated']),
  item('b1908-steamed-bun', 'Steamed BBQ Pork Bun', 'Bakery 1908', 'snacks', '1 bun', 260, 10, 38, 7, 520, ['dim sum', 'estimated']),
  item('b1908-milk-tea', 'Milk Tea (regular)', 'Bakery 1908', 'snacks', '1 drink', 280, 4, 48, 8, 80, ['boba', 'tea', 'estimated']),
  item('b1908-cheesecake', 'Cheesecake Slice', 'Bakery 1908', 'snacks', '1 slice', 420, 7, 38, 28, 320, ['dessert', 'estimated']),

  // ——— Beefy King (Orlando roast beef; sandwich analogs) ———
  item('bk-roast-jr', 'Roast Beef Sandwich (Junior)', 'Beefy King', 'sandwiches', '1 sandwich', 380, 28, 32, 16, 980, ['roast beef', 'estimated']),
  item('bk-roast-reg', 'Roast Beef Sandwich (Regular)', 'Beefy King', 'sandwiches', '1 sandwich', 485, 36, 35, 22, 1280, ['roast beef', 'estimated']),
  item('bk-roast-xl', 'Roast Beef Sandwich (X-Large)', 'Beefy King', 'sandwiches', '1 sandwich', 620, 48, 38, 28, 1620, ['roast beef', 'estimated']),
  item('bk-ham', 'Ham Sandwich (Regular)', 'Beefy King', 'sandwiches', '1 sandwich', 420, 28, 36, 18, 1420, ['estimated']),
  item('bk-turkey', 'Turkey Breast Sandwich (Regular)', 'Beefy King', 'sandwiches', '1 sandwich', 400, 32, 36, 14, 1320, ['estimated']),
  item('bk-pastrami', 'Pastrami Sandwich (Regular)', 'Beefy King', 'sandwiches', '1 sandwich', 520, 34, 36, 26, 1680, ['pastrami', 'estimated']),
  item('bk-corned', 'Corned Beef Sandwich (Regular)', 'Beefy King', 'sandwiches', '1 sandwich', 500, 32, 36, 24, 1580, ['estimated']),
  item('bk-bbq-beef', 'Bar-B-Q Beef Sandwich (Regular)', 'Beefy King', 'sandwiches', '1 sandwich', 540, 34, 42, 24, 1480, ['bbq', 'estimated']),
  item('bk-bbq-pork', 'Bar-B-Q Pork Sandwich (Regular)', 'Beefy King', 'sandwiches', '1 sandwich', 510, 30, 42, 22, 1380, ['bbq', 'estimated']),
  item('bk-reuben', 'Hot Reuben Sandwich', 'Beefy King', 'sandwiches', '1 sandwich', 620, 34, 42, 32, 1780, ['reuben', 'estimated']),
  item('bk-spuds', 'Beefy Spuds (tater tots, regular)', 'Beefy King', 'snacks', '1 order', 380, 4, 42, 22, 720, ['tots', 'estimated']),
  item('bk-chili', 'Cup of Chili', 'Beefy King', 'lunch', '1 cup', 220, 14, 16, 12, 680, ['chili', 'estimated']),
  item('bk-shake', 'Hand-Spun Milkshake (regular)', 'Beefy King', 'snacks', '1 shake', 520, 12, 68, 22, 280, ['shake', 'estimated']),

  // ——— World of Beer (published Nov 2024 nutrition) ———
  item('wob-wings-10', 'WOB Chicken Wings (10)', 'World of Beer', 'lunch', '10 wings', 911, 61, 16, 65, 2136, ['wings']),
  item('wob-wings-5', 'WOB Chicken Wings (5)', 'World of Beer', 'snacks', '5 wings', 458, 31, 8, 33, 1074, ['wings']),
  item('wob-boneless', 'Boneless Wings', 'World of Beer', 'lunch', '1 serving', 650, 83, 45, 11, 3694, ['wings']),
  item('wob-pretzel-cheese', 'German Pretzel with Beer Cheese', 'World of Beer', 'snacks', '1 serving', 1100, 26, 196, 21, 20388, ['pretzel']),
  item('wob-nachos', 'Beer Cheese Nachos', 'World of Beer', 'snacks', '1 serving', 1252, 37, 157, 51, 2181, ['nachos']),
  item('wob-truffle-fries', 'Parmesan Truffle Fries', 'World of Beer', 'snacks', '1 serving', 1000, 10, 65, 80, 1722, ['fries']),
  item('wob-mac-bites', 'Mac and Cheese Bites', 'World of Beer', 'snacks', '1 serving', 771, 9, 31, 66, 1310, ['mac']),
  item('wob-spinach-dip', 'Spinach and Artichoke Dip', 'World of Beer', 'snacks', '1 serving', 1045, 29, 79, 67, 1791, ['dip']),
  item('wob-byo-burger', 'BYO Burger', 'World of Beer', 'sandwiches', '1 burger', 638, 42, 41, 33, 5331, ['burger']),
  item('wob-brisket-burger', 'Smoked BBQ Brisket Burger', 'World of Beer', 'sandwiches', '1 burger', 1084, 63, 74, 59, 7076, ['burger', 'brisket']),
  item('wob-black-blue', 'Black and Blue Burger', 'World of Beer', 'sandwiches', '1 burger', 1085, 55, 49, 73, 3177, ['burger']),
  item('wob-french-dip', 'French Dip Sandwich', 'World of Beer', 'sandwiches', '1 sandwich', 1256, 53, 71, 85, 2383, ['sandwich']),
  item('wob-buff-chicken', 'Buffalo Chicken Sandwich', 'World of Beer', 'sandwiches', '1 sandwich', 829, 44, 82, 32, 3684, ['sandwich', 'buffalo']),
  item('wob-flat-bbq', 'Chipotle BBQ Chicken Flatbread', 'World of Beer', 'dinner', '1 flatbread', 814, 44, 94, 29, 1892, ['flatbread']),
  item('wob-cobb', 'WOB Cobb Salad', 'World of Beer', 'lunch', '1 salad', 1028, 50, 87, 53, 3620, ['salad']),
  item('wob-caesar-chicken', 'Caesar Salad with Grilled Chicken', 'World of Beer', 'lunch', '1 salad', 686, 43, 25, 44, 2326, ['salad']),
  item('wob-chili-bowl', 'Colorado Chili with Fixings (bowl)', 'World of Beer', 'lunch', '1 bowl', 472, 34, 32, 23, 1596, ['chili']),
  item('wob-steak-frites', 'Steak Frites', 'World of Beer', 'dinner', '1 entrée', 1561, 39, 46, 134, 2676, ['steak']),
  item('wob-ipa-salmon', 'IPA Salmon', 'World of Beer', 'dinner', '1 entrée', 654, 44, 33, 36, 1478, ['salmon']),
  item('wob-street-tacos', 'Crispy Beer-Brined Chicken Street Tacos (3)', 'World of Beer', 'lunch', '3 tacos', 895, 44, 95, 33, 3417, ['tacos']),

  // ——— BENTO Asian Kitchen + Sushi (Mar 2024 nutrition; composed builds) ———
  item('bento-box-white', 'Bento Box Base (white rice, noodles, veggies)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 box base', 590, 10, 77, 31, 1060, ['bento', 'asian']),
  item('bento-teriyaki-chicken-box', 'Teriyaki Chicken Bento Box', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 box', 1000, 67, 107, 44, 1755, ['bento', 'teriyaki', 'chicken']),
  item('bento-orange-chicken-box', 'Orange Chicken Bento Box', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 box', 1380, 43, 182, 66, 2260, ['bento', 'orange', 'chicken']),
  item('bento-rice-bowl-white', 'Rice Bowl with White Rice (base)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 bowl base', 390, 7, 85, 1, 0, ['bowl']),
  item('bento-fried-rice-bowl', 'Rice Bowl with Fried Rice (base)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 bowl base', 780, 18, 100, 35, 830, ['bowl', 'fried rice']),
  item('bento-lo-mein-bowl', 'Noodle Bowl with Lo Mein (base)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 bowl base', 390, 10, 69, 8, 760, ['noodles']),
  item('bento-chicken-wok', 'Wok Chicken (protein add-on)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 portion', 280, 41, 0, 12, 85, ['chicken']),
  item('bento-steak-wok', 'Wok Steak (protein add-on)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 portion', 340, 37, 0, 21, 80, ['steak']),
  item('bento-pad-thai', 'Pad Thai Noodle Bowl (no protein)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 bowl', 840, 27, 130, 24, 1120, ['pad thai', 'noodles']),
  item('bento-shanghai-lo-mein', 'Shanghai Lo Mein (no protein)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 order', 390, 10, 69, 8, 760, ['lo mein']),
  item('bento-cali-roll', 'California Roll (8 pcs)', 'BENTO Asian Kitchen + Sushi', 'lunch', '8 pieces', 190, 6, 37, 2, 800, ['sushi', 'roll']),
  item('bento-spicy-tuna', 'Spicy Tuna Roll (8 pcs)', 'BENTO Asian Kitchen + Sushi', 'lunch', '8 pieces', 320, 13, 38, 10, 1260, ['sushi', 'tuna']),
  item('bento-rainbow', 'Rainbow Roll (8 pcs)', 'BENTO Asian Kitchen + Sushi', 'lunch', '8 pieces', 280, 16, 38, 6, 820, ['sushi']),
  item('bento-volcano', 'Volcano Roll', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 roll', 900, 21, 42, 71, 1930, ['sushi']),
  item('bento-crunch', 'Crunch Roll', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 roll', 960, 27, 103, 47, 2520, ['sushi']),
  item('bento-poke-salmon', 'Poké Bowl (sushi rice + soy salmon + avocado)', 'BENTO Asian Kitchen + Sushi', 'lunch', '1 bowl', 390, 14, 52, 12, 390, ['poke', 'salmon']),
  item('bento-dumplings-fried', 'Pork Dumplings Fried (6)', 'BENTO Asian Kitchen + Sushi', 'snacks', '6 pieces', 680, 16, 62, 43, 2650, ['dumplings']),
  item('bento-egg-rolls', 'Pork Egg Rolls', 'BENTO Asian Kitchen + Sushi', 'snacks', '1 order', 450, 14, 60, 19, 1600, ['egg rolls']),
  item('bento-edamame', 'Edamame (large)', 'BENTO Asian Kitchen + Sushi', 'snacks', '1 order', 460, 37, 33, 18, 380, ['edamame']),
  item('bento-milk-tea', 'Jasmine Milk Tea (16 oz w/ boba)', 'BENTO Asian Kitchen + Sushi', 'snacks', '16 oz', 270, 0, 58, 5, 15, ['boba', 'tea']),
  item('bento-thai-tea', 'Thai Tea (16 oz w/ boba)', 'BENTO Asian Kitchen + Sushi', 'snacks', '16 oz', 300, 0, 53, 9, 20, ['boba', 'tea']),

  // ——— Summer Palace (Chinese; Panda / typical Chinese restaurant analogs) ———
  item('sp-orange-chicken', 'Orange Chicken', 'Summer Palace', 'dinner', '1 entrée', 490, 25, 51, 23, 820, ['chinese', 'estimated']),
  item('sp-general-tso', "General Tso's Chicken", 'Summer Palace', 'dinner', '1 entrée', 520, 26, 48, 26, 980, ['chinese', 'estimated']),
  item('sp-mongolian-beef', 'Mongolian Beef', 'Summer Palace', 'dinner', '1 entrée', 480, 28, 36, 26, 1120, ['chinese', 'estimated']),
  item('sp-beef-veg', 'Beef with Chinese Vegetables', 'Summer Palace', 'dinner', '1 entrée', 420, 32, 22, 24, 980, ['chinese', 'estimated']),
  item('sp-kung-pao', 'Kung Pao Chicken', 'Summer Palace', 'dinner', '1 entrée', 460, 28, 32, 24, 1080, ['chinese', 'estimated']),
  item('sp-sesame-chicken', 'Sesame Chicken', 'Summer Palace', 'dinner', '1 entrée', 500, 26, 48, 24, 920, ['chinese', 'estimated']),
  item('sp-fried-rice', 'House Special Fried Rice', 'Summer Palace', 'lunch', '1 order', 620, 22, 78, 24, 1180, ['chinese', 'fried rice', 'estimated']),
  item('sp-lo-mein', 'Chicken Lo Mein', 'Summer Palace', 'lunch', '1 order', 580, 28, 68, 22, 1420, ['chinese', 'lo mein', 'estimated']),
  item('sp-egg-roll', 'Egg Roll', 'Summer Palace', 'snacks', '1 roll', 200, 6, 22, 10, 420, ['chinese', 'estimated']),
  item('sp-wonton-soup', 'Wonton Soup', 'Summer Palace', 'lunch', '1 bowl', 180, 12, 18, 6, 980, ['soup', 'chinese', 'estimated']),
  item('sp-egg-drop', 'Egg Drop Soup', 'Summer Palace', 'lunch', '1 bowl', 90, 6, 8, 4, 720, ['soup', 'chinese', 'estimated']),
  item('sp-egg-foo-young', 'Chicken Egg Foo Young', 'Summer Palace', 'dinner', '1 order', 480, 24, 22, 32, 1120, ['chinese', 'estimated']),
  item('sp-cali-roll', 'California Roll', 'Summer Palace', 'lunch', '1 roll', 280, 8, 38, 10, 680, ['sushi', 'estimated']),
  item('sp-summer-palace-roll', 'Summer Palace Roll', 'Summer Palace', 'lunch', '1 roll', 420, 18, 42, 18, 920, ['sushi', 'estimated']),

  // ——— Gator's Dockside (sports bar; wing/rib analogs) ———
  item('gd-wings-8', 'Chicken Wings (8, buffalo)', "Gator's Dockside", 'lunch', '8 wings', 720, 48, 8, 54, 1680, ['wings', 'estimated']),
  item('gd-wings-10', 'Chicken Wings (10, buffalo)', "Gator's Dockside", 'lunch', '10 wings', 900, 60, 10, 68, 2100, ['wings', 'estimated']),
  item('gd-boneless', 'Boneless Wings (regular order)', "Gator's Dockside", 'lunch', '1 order', 680, 42, 48, 36, 1860, ['wings', 'estimated']),
  item('gd-ribs-half', 'Half Rack BBQ Ribs', "Gator's Dockside", 'dinner', '1/2 rack', 780, 48, 28, 52, 1680, ['ribs', 'bbq', 'estimated']),
  item('gd-rib-wing', 'Dockside Rib & Wing Platter', "Gator's Dockside", 'dinner', '1 platter', 1240, 72, 36, 82, 2480, ['ribs', 'wings', 'estimated']),
  item('gd-chicken-blt', 'Chicken BLT Wrap', "Gator's Dockside", 'sandwiches', '1 wrap', 720, 38, 52, 38, 1680, ['wrap', 'estimated']),
  item('gd-tenders', 'Chicken Tenders', "Gator's Dockside", 'lunch', '1 order', 640, 42, 48, 32, 1580, ['tenders', 'estimated']),
  item('gd-gator-taters', 'Gator Taters', "Gator's Dockside", 'snacks', '1 order', 620, 12, 58, 38, 1280, ['fries', 'estimated']),
  item('gd-seabreeze', 'Seabreeze Salad', "Gator's Dockside", 'lunch', '1 salad', 660, 28, 42, 38, 1280, ['salad', 'estimated']),
  item('gd-buffalo-taco', 'Buffalo Chicken Touchdown Tacos', "Gator's Dockside", 'lunch', '1 order', 580, 32, 48, 28, 1420, ['tacos', 'estimated']),
  item('gd-bourbon-taco', 'Bourbon BBQ Pork Touchdown Tacos', "Gator's Dockside", 'lunch', '1 order', 620, 28, 52, 32, 1480, ['tacos', 'bbq', 'estimated']),
  item('gd-gator-bowl', 'Gator Bowl (chicken, yellow rice)', "Gator's Dockside", 'lunch', '1 bowl', 720, 42, 68, 28, 1380, ['bowl', 'estimated']),
  item('gd-fish-sandwich', 'Fried Fish Sandwich', "Gator's Dockside", 'sandwiches', '1 sandwich', 780, 36, 62, 42, 1520, ['fish', 'estimated']),

  // ——— Se7en Bites (Orlando Southern brunch; ABE / First Watch analogs) ———
  item('s7-chicken-biscuit', 'Signature Chicken Biscuit', 'Se7en Bites', 'breakfast', '1 sandwich', 720, 32, 58, 38, 1680, ['biscuit', 'chicken', 'estimated']),
  item('s7-minnie-pearl', 'Minnie Pearl (chicken & waffles)', 'Se7en Bites', 'breakfast', '1 plate', 1180, 48, 112, 58, 2100, ['waffle', 'chicken', 'estimated']),
  item('s7-3-pigs', '3 Little Pigs Breakfast', 'Se7en Bites', 'breakfast', '1 plate', 980, 42, 72, 56, 2480, ['biscuit', 'gravy', 'estimated']),
  item('s7-pancakes', "Grammies Buttermilk Pancakes", 'Se7en Bites', 'breakfast', '1 stack', 820, 18, 118, 28, 1120, ['pancakes', 'estimated']),
  item('s7-benedict', 'Se7en Benedict', 'Se7en Bites', 'breakfast', '1 order', 780, 34, 48, 48, 1860, ['benedict', 'estimated']),
  item('s7-trimester', '7th Trimester (biscuit, egg, mac)', 'Se7en Bites', 'breakfast', '1 plate', 980, 38, 72, 58, 2280, ['mac', 'biscuit', 'estimated']),
  item('s7-pot-pie', 'Chicken Pot Pie', 'Se7en Bites', 'lunch', '1 pie', 720, 32, 58, 38, 1480, ['pot pie', 'estimated']),
  item('s7-mac', '5 Cheese Mac N\' Cheese', 'Se7en Bites', 'lunch', '1 order', 680, 24, 52, 42, 1320, ['mac', 'estimated']),
  item('s7-cheezy-q', "Cheezy-Q (pulled pork + mac)", 'Se7en Bites', 'sandwiches', '1 sandwich', 980, 42, 78, 52, 1980, ['bbq', 'pork', 'estimated']),
  item('s7-farmers', 'Farmers Breakfast Sandwich', 'Se7en Bites', 'breakfast', '1 sandwich', 640, 32, 42, 36, 1520, ['estimated']),
  item('s7-cookie', 'Chocolate Chip Cookie', 'Se7en Bites', 'snacks', '1 cookie', 280, 3, 36, 14, 180, ['dessert', 'estimated']),
  item('s7-pie', 'Slice of Pie (house)', 'Se7en Bites', 'snacks', '1 slice', 480, 6, 58, 24, 320, ['dessert', 'pie', 'estimated']),

  // ——— Peers: Black Bean Deli + Pig Floyd's ———
  item('bbd-medianoche', 'Medianoche', 'Black Bean Deli', 'sandwiches', '1 sandwich', 620, 32, 48, 32, 1480, ['cuban', 'estimated']),
  item('bbd-cubano', 'Cubano', 'Black Bean Deli', 'sandwiches', '1 sandwich', 680, 36, 52, 34, 1620, ['cuban', 'estimated']),
  item('bbd-pan-con-bistec', 'Pan Con Bistec', 'Black Bean Deli', 'sandwiches', '1 sandwich', 720, 38, 54, 36, 1580, ['cuban', 'steak', 'estimated']),
  item('bbd-ropa', 'Ropa Vieja Plate', 'Black Bean Deli', 'dinner', '1 plate', 780, 42, 68, 32, 1420, ['cuban', 'estimated']),
  item('bbd-lechon', 'Lechon Asado Plate', 'Black Bean Deli', 'dinner', '1 plate', 820, 40, 62, 40, 1380, ['cuban', 'pork', 'estimated']),
  item('bbd-empanada', 'Beef Empanada', 'Black Bean Deli', 'snacks', '1 empanada', 290, 11, 26, 16, 460, ['cuban', 'estimated']),
  item('bbd-black-beans', 'Black Beans & Rice', 'Black Bean Deli', 'lunch', '1 side', 320, 12, 54, 6, 680, ['cuban', 'estimated']),
  item('pf-brisket', 'Smoked Brisket Plate', "Pig Floyd's Urban Barbakoa", 'dinner', '1 plate', 860, 52, 48, 48, 1680, ['bbq', 'brisket', 'estimated']),
  item('pf-pulled-pork', 'Pulled Pork Sandwich', "Pig Floyd's Urban Barbakoa", 'sandwiches', '1 sandwich', 620, 36, 48, 28, 1420, ['bbq', 'pork', 'estimated']),
  item('pf-ribs', 'St. Louis Ribs (half rack)', "Pig Floyd's Urban Barbakoa", 'dinner', '1/2 rack', 820, 48, 24, 56, 1580, ['bbq', 'ribs', 'estimated']),
  item('pf-burnt-ends', 'Burnt Ends', "Pig Floyd's Urban Barbakoa", 'lunch', '1 order', 680, 42, 28, 42, 1480, ['bbq', 'estimated']),
  item('pf-mac', 'Mac & Cheese', "Pig Floyd's Urban Barbakoa", 'snacks', '1 side', 420, 14, 36, 24, 880, ['mac', 'estimated']),
  item('pf-collards', 'Collard Greens', "Pig Floyd's Urban Barbakoa", 'snacks', '1 side', 140, 6, 14, 8, 720, ['sides', 'estimated']),
];
