import type { FastFoodCategory, FastFoodItem } from './fastFoodMenu';

/**
 * Florida / Caribbean favorites that were still missing from the catalog.
 * Juici Patties uses UK retail nutrition labels scaled to one 135 g patty.
 * Doubles use the Trinidad street-food study (~300 kcal per double).
 * Bahama Breeze calories follow the chain's published menu / nutrition guides.
 * Charlie's Pastries, Kingston 5, Singh's Roti Shop, Peppa's Jerk Chicken,
 * Chef Creole, True Island Grille, Taste of Jamaica, Caribbean Sunshine Bakery,
 * Miss Lily's, Jerk at Nite, Jerk King, Ja' Grill, The Jerk Shack,
 * Jamaican Jerk Biz, Mark's Jamaican Bar & Grill, Negril Jamaican Restaurant,
 * Negril Jamaican Eatery, Scotch Bonnet Kitchen, Reggae Pot, Island Spice,
 * Peppers Jamaican, Bouka's, and Potwah do not publish full macros; those plates
 * are calibrated to Golden Krust reference values so users can still log typical orders.
 */
const item = (
  id: string,
  name: string,
  restaurant: string,
  category: FastFoodCategory,
  serving: string,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  sodium: number,
  keywords?: string[],
): FastFoodItem => ({ id, name, restaurant, category, serving, calories, protein, carbs, fat, sodium, ...(keywords ? { keywords } : {}) });

export const CARIBBEAN_FAST_FOOD_ITEMS: FastFoodItem[] = [
  // Juici Patties — retail label per 100 g scaled to 135 g patty
  item('juici-beef-patty', 'Beef Patty', 'Juici Patties', 'lunch', '1 patty', 410, 10, 41, 24, 540, ['jamaican', 'caribbean', 'juicy']),
  item('juici-chicken-patty', 'Chicken Patty', 'Juici Patties', 'lunch', '1 patty', 380, 10, 42, 20, 540, ['jamaican', 'caribbean', 'juicy']),
  item('juici-veggie-patty', 'Vegetable Patty', 'Juici Patties', 'lunch', '1 patty', 320, 7, 38, 16, 480, ['jamaican', 'vegetarian', 'juicy']),
  item('juici-shrimp-patty', 'Shrimp Patty', 'Juici Patties', 'lunch', '1 patty', 360, 11, 40, 18, 620, ['jamaican', 'seafood', 'juicy']),
  item('juici-coco-bread', 'Coco Bread', 'Juici Patties', 'snacks', '1 piece', 400, 8, 58, 15, 470, ['jamaican', 'caribbean']),
  item('juici-patty-coco', 'Beef Patty in Coco Bread', 'Juici Patties', 'lunch', '1 sandwich', 810, 18, 99, 39, 1010, ['jamaican', 'caribbean']),
  item('juici-breakfast-patty', 'Breakfast Patty', 'Juici Patties', 'breakfast', '1 patty', 390, 12, 38, 20, 580, ['jamaican', 'egg']),

  // Charlie's Pastries (Lauderhill / South Florida) — bakery analogs to Golden Krust published items
  item('charlies-beef-patty', 'Spicy Beef Patty', "Charlie's Pastries", 'lunch', '1 patty', 490, 12, 50, 24, 690, ['jamaican', 'caribbean', 'charlie']),
  item('charlies-mild-beef', 'Mild Beef Patty', "Charlie's Pastries", 'lunch', '1 patty', 470, 12, 49, 23, 660, ['jamaican', 'caribbean']),
  item('charlies-chicken-patty', 'Curry Chicken Patty', "Charlie's Pastries", 'lunch', '1 patty', 380, 12, 42, 18, 700, ['jamaican', 'caribbean']),
  item('charlies-jerk-chicken-patty', 'Jerk Chicken Patty', "Charlie's Pastries", 'lunch', '1 patty', 400, 14, 40, 20, 720, ['jamaican', 'jerk']),
  item('charlies-veggie-patty', 'Vegetable Patty', "Charlie's Pastries", 'lunch', '1 patty', 260, 6, 30, 12, 540, ['jamaican', 'vegetarian']),
  item('charlies-callaloo-patty', 'Callaloo & Saltfish Patty', "Charlie's Pastries", 'lunch', '1 patty', 340, 12, 36, 16, 780, ['jamaican', 'caribbean']),
  item('charlies-coco-bread', 'Coco Bread', "Charlie's Pastries", 'snacks', '1 piece', 400, 8, 58, 15, 470, ['jamaican']),
  item('charlies-patty-coco', 'Beef Patty in Coco Bread', "Charlie's Pastries", 'lunch', '1 sandwich', 870, 20, 108, 39, 1160, ['jamaican', 'caribbean']),
  item('charlies-hard-dough', 'Hard Dough Bread (slice)', "Charlie's Pastries", 'snacks', '1 slice', 140, 4, 28, 2, 220, ['jamaican', 'bread']),
  item('charlies-bulla', 'Bulla Cake', "Charlie's Pastries", 'snacks', '1 cake', 220, 4, 42, 5, 180, ['jamaican', 'dessert']),

  // Kingston 5 (Lake Nona / Orlando) — patties + fusion baos/tacos/platters
  item('kingston5-beef-patty', 'Beef Patty', 'Kingston 5', 'lunch', '1 patty', 490, 12, 50, 24, 690, ['jamaican', 'orlando', 'lake nona']),
  item('kingston5-jerk-chicken-patty', 'Jerk Chicken Patty', 'Kingston 5', 'lunch', '1 patty', 400, 14, 40, 20, 720, ['jamaican', 'jerk']),
  item('kingston5-veggie-patty', 'Veggie Patty', 'Kingston 5', 'lunch', '1 patty', 260, 6, 30, 12, 540, ['jamaican', 'vegetarian']),
  item('kingston5-oxtail-bao', 'Oxtail Bao', 'Kingston 5', 'lunch', '1 bao', 520, 22, 48, 26, 980, ['jamaican', 'bao', 'oxtail']),
  item('kingston5-brown-stew-bao', 'Brown Stew Chicken Bao', 'Kingston 5', 'lunch', '1 bao', 430, 20, 44, 18, 900, ['jamaican', 'bao']),
  item('kingston5-curry-bao', 'Curry Chicken Bao', 'Kingston 5', 'lunch', '1 bao', 420, 20, 44, 17, 880, ['jamaican', 'bao', 'curry']),
  item('kingston5-oxtail-taco', 'Oxtail Street Taco', 'Kingston 5', 'lunch', '1 taco', 500, 22, 42, 26, 960, ['jamaican', 'taco', 'oxtail']),
  item('kingston5-brown-stew-taco', 'Brown Stew Chicken Taco', 'Kingston 5', 'lunch', '1 taco', 420, 20, 38, 18, 880, ['jamaican', 'taco']),
  item('kingston5-curry-taco', 'Curry Chicken Taco', 'Kingston 5', 'lunch', '1 taco', 410, 20, 38, 17, 860, ['jamaican', 'taco', 'curry']),
  item('kingston5-oxtail-platter', 'Sweet Oxtail Platter (rice & peas)', 'Kingston 5', 'dinner', '1 platter', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('kingston5-brown-stew-platter', 'Brown Stew Chicken Platter', 'Kingston 5', 'dinner', '1 platter', 680, 36, 62, 28, 1540, ['jamaican']),
  item('kingston5-curry-platter', 'Curry Chicken Platter', 'Kingston 5', 'dinner', '1 platter', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('kingston5-plantains', 'Sweet Plantains', 'Kingston 5', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'maduros']),

  // Singh's Roti Shop (Orlando / South Florida Indo-Caribbean)
  item('singhs-doubles', 'Doubles', "Singh's Roti Shop", 'snacks', '1 doubles', 300, 10, 36, 12, 350, ['trinidad', 'caribbean', 'channa']),
  item('singhs-aloo-pie', 'Aloo Pie', "Singh's Roti Shop", 'snacks', '1 pie', 270, 5, 36, 12, 420, ['trinidad', 'potato']),
  item('singhs-pholourie', 'Pholourie (order)', "Singh's Roti Shop", 'snacks', '1 order', 220, 6, 28, 10, 380, ['trinidad']),
  item('singhs-chicken-roti', 'Curry Chicken Roti', "Singh's Roti Shop", 'lunch', '1 roti', 520, 36, 60, 18, 900, ['trinidad', 'roti', 'curry']),
  item('singhs-boneless-chicken-roti', 'Boneless Curry Chicken Roti', "Singh's Roti Shop", 'lunch', '1 roti', 540, 38, 58, 20, 920, ['trinidad', 'roti']),
  item('singhs-goat-roti', 'Curry Goat Roti', "Singh's Roti Shop", 'dinner', '1 roti', 580, 34, 58, 24, 980, ['trinidad', 'roti', 'goat']),
  item('singhs-beef-roti', 'Curry Beef Roti', "Singh's Roti Shop", 'dinner', '1 roti', 560, 32, 58, 22, 960, ['trinidad', 'roti']),
  item('singhs-shrimp-roti', 'Curry Shrimp Roti', "Singh's Roti Shop", 'dinner', '1 roti', 500, 28, 56, 18, 1100, ['trinidad', 'roti', 'shrimp']),
  item('singhs-oxtail', 'Oxtail with Rice or Roti', "Singh's Roti Shop", 'dinner', '1 plate', 920, 48, 70, 46, 1400, ['trinidad', 'oxtail']),
  item('singhs-curry-chicken-plate', 'Curry Chicken with Rice', "Singh's Roti Shop", 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['trinidad', 'curry']),
  item('singhs-dhal-puri', 'Dhal Puri (roti shell)', "Singh's Roti Shop", 'snacks', '1 roti', 280, 8, 48, 6, 420, ['trinidad', 'roti']),
  item('singhs-bake-shark', 'Bake and Shark', "Singh's Roti Shop", 'sandwiches', '1 sandwich', 620, 28, 58, 30, 980, ['trinidad', 'fish']),

  // Bahama Breeze Island Grille — published menu calories (Darden)
  item('bahama-breeze-jerk-chicken', 'Jamaican Jerk Chicken (rice, beans, plantains)', 'Bahama Breeze', 'dinner', '1 plate', 1490, 72, 120, 68, 2440, ['caribbean', 'jerk', 'jamaican']),
  item('bahama-breeze-jerk-pasta', 'Jerk Chicken Pasta (full)', 'Bahama Breeze', 'dinner', '1 full portion', 1300, 58, 98, 68, 2260, ['caribbean', 'jerk', 'pasta']),
  item('bahama-breeze-jerk-pasta-light', 'Jerk Chicken Pasta (lighter)', 'Bahama Breeze', 'lunch', '1 lighter portion', 700, 38, 58, 32, 1190, ['caribbean', 'jerk', 'pasta']),
  item('bahama-breeze-jerk-shrimp-pasta', 'Jerk Shrimp Pasta (full)', 'Bahama Breeze', 'dinner', '1 full portion', 1270, 52, 96, 66, 2200, ['caribbean', 'jerk', 'shrimp', 'pasta']),
  item('bahama-breeze-jerk-shrimp-pasta-light', 'Jerk Shrimp Pasta (lighter)', 'Bahama Breeze', 'lunch', '1 lighter portion', 680, 36, 56, 30, 1400, ['caribbean', 'jerk', 'shrimp']),
  item('bahama-breeze-coconut-shrimp-app', 'Coconut Shrimp (appetizer)', 'Bahama Breeze', 'snacks', '1 appetizer', 610, 22, 52, 34, 980, ['caribbean', 'shrimp', 'appetizer']),
  item('bahama-breeze-coconut-shrimp', 'Coconut Shrimp (entree with rice & broccoli)', 'Bahama Breeze', 'dinner', '1 plate', 1160, 38, 106, 58, 2200, ['caribbean', 'shrimp']),
  item('bahama-breeze-firecracker-shrimp', 'Firecracker Shrimp', 'Bahama Breeze', 'snacks', '1 appetizer', 1350, 36, 98, 82, 2400, ['caribbean', 'shrimp', 'spicy']),
  item('bahama-breeze-island-hopper', 'Island Hopper', 'Bahama Breeze', 'snacks', '1 appetizer', 780, 36, 48, 48, 2100, ['caribbean', 'wings', 'sampler']),
  item('bahama-breeze-jerk-wings', 'Jamaican Grilled Chicken Wings (4)', 'Bahama Breeze', 'snacks', '4 wings', 780, 48, 12, 56, 2640, ['caribbean', 'jerk', 'wings']),
  item('bahama-breeze-black-bean-soup-cup', 'Cuban Black Bean Soup (cup)', 'Bahama Breeze', 'lunch', '1 cup', 220, 10, 28, 8, 720, ['caribbean', 'cuban', 'soup']),
  item('bahama-breeze-black-bean-soup-bowl', 'Cuban Black Bean Soup (bowl)', 'Bahama Breeze', 'lunch', '1 bowl', 440, 18, 52, 14, 1400, ['caribbean', 'cuban', 'soup']),
  item('bahama-breeze-chowder-cup', 'Bahamian Seafood Chowder (cup)', 'Bahama Breeze', 'lunch', '1 cup', 230, 12, 18, 12, 880, ['caribbean', 'chowder', 'seafood']),
  item('bahama-breeze-chowder-bowl', 'Bahamian Seafood Chowder (bowl)', 'Bahama Breeze', 'lunch', '1 bowl', 470, 24, 32, 24, 1680, ['caribbean', 'chowder', 'seafood']),
  item('bahama-breeze-ribs-half', 'Baby Back Ribs (half rack with fries)', 'Bahama Breeze', 'dinner', 'half rack', 1310, 62, 78, 78, 2100, ['caribbean', 'ribs', 'bbq']),
  item('bahama-breeze-ribs-full', 'Baby Back Ribs (full rack with fries)', 'Bahama Breeze', 'dinner', 'full rack', 1970, 92, 98, 118, 2800, ['caribbean', 'ribs', 'bbq']),
  item('bahama-breeze-churrasco', 'Skirt Steak Churrasco (rice, beans, plantains)', 'Bahama Breeze', 'dinner', '1 plate', 1060, 58, 72, 58, 1980, ['caribbean', 'steak', 'churrasco']),
  item('bahama-breeze-paella', 'Seafood Paella', 'Bahama Breeze', 'dinner', '1 plate', 940, 52, 88, 36, 2800, ['caribbean', 'seafood', 'paella']),
  item('bahama-breeze-salmon-tequila', 'Tequila Sunburn Glazed Salmon', 'Bahama Breeze', 'dinner', '1 plate', 840, 48, 62, 38, 1650, ['caribbean', 'salmon']),
  item('bahama-breeze-grilled-salmon', 'Grilled Salmon (yellow rice & broccoli)', 'Bahama Breeze', 'dinner', '1 plate', 870, 52, 58, 42, 1400, ['caribbean', 'salmon']),
  item('bahama-breeze-jerk-sandwich', 'Jerk Chicken Sandwich', 'Bahama Breeze', 'sandwiches', '1 sandwich', 1020, 48, 78, 52, 2100, ['caribbean', 'jerk', 'sandwich']),
  item('bahama-breeze-grilled-chicken-sandwich', 'Grilled Chicken Sandwich', 'Bahama Breeze', 'sandwiches', '1 sandwich', 420, 38, 36, 14, 980, ['caribbean', 'chicken', 'sandwich']),
  item('bahama-breeze-mahi-tacos', 'Mahi Tacos (3)', 'Bahama Breeze', 'lunch', '3 tacos', 620, 36, 52, 28, 1400, ['caribbean', 'mahi', 'tacos']),
  item('bahama-breeze-coconut-shrimp-tacos', 'Coconut Shrimp Tacos (3)', 'Bahama Breeze', 'lunch', '3 tacos', 1170, 32, 98, 68, 2200, ['caribbean', 'shrimp', 'tacos']),
  item('bahama-breeze-ropa-vieja', 'Ropa Vieja Tostones', 'Bahama Breeze', 'dinner', '1 plate', 1350, 48, 110, 72, 2400, ['caribbean', 'cuban', 'beef']),
  item('bahama-breeze-stuffed-plantain', 'Jamaican Stuffed Plantain Bowl', 'Bahama Breeze', 'lunch', '1 bowl', 1140, 34, 124, 52, 2560, ['caribbean', 'jamaican', 'plantain']),

  // Peppa's Jerk Chicken — Florida Jamaican spots (macros calibrated to Golden Krust plates)
  item('peppas-jerk-chicken-only', 'Jerk Chicken Only (leg quarter)', "Peppa's Jerk Chicken", 'dinner', '1 leg quarter', 450, 42, 4, 28, 1200, ['jamaican', 'jerk', 'caribbean', 'peppa']),
  item('peppas-jerk-chicken-meal', 'Jerk Chicken Meal (rice + side)', "Peppa's Jerk Chicken", 'dinner', '1 meal', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'caribbean', 'peppa']),
  item('peppas-jerk-mac', 'Jerk Chicken with Mac & Cheese', "Peppa's Jerk Chicken", 'dinner', '1 plate', 980, 48, 88, 48, 2100, ['jamaican', 'jerk', 'mac']),
  item('peppas-jerk-fries', 'Jerk Chicken with French Fries', "Peppa's Jerk Chicken", 'dinner', '1 plate', 920, 46, 78, 46, 2000, ['jamaican', 'jerk', 'fries']),
  item('peppas-jerk-salad', 'Jerk Chicken over Salad', "Peppa's Jerk Chicken", 'lunch', '1 salad', 520, 44, 18, 28, 1400, ['jamaican', 'jerk', 'salad']),
  item('peppas-oxtail-dinner', 'Oxtail Dinner (rice + salad)', "Peppa's Jerk Chicken", 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail', 'caribbean']),
  item('peppas-curry-goat', 'Curry Goat Dinner', "Peppa's Jerk Chicken", 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('peppas-curry-chicken', 'Curry Chicken Dinner', "Peppa's Jerk Chicken", 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry', 'chicken']),
  item('peppas-brown-stew', 'Brown Stew Chicken Dinner', "Peppa's Jerk Chicken", 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('peppas-escovitch', 'Escovitch Fish Dinner', "Peppa's Jerk Chicken", 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'fish', 'escovitch']),
  item('peppas-jerk-salmon', 'Jerk Salmon Dinner', "Peppa's Jerk Chicken", 'dinner', '1 plate', 780, 44, 58, 36, 1500, ['jamaican', 'jerk', 'salmon']),
  item('peppas-jerk-shrimp', 'Jerk Shrimp Dinner', "Peppa's Jerk Chicken", 'dinner', '1 plate', 700, 38, 56, 30, 1680, ['jamaican', 'jerk', 'shrimp']),
  item('peppas-festival', 'Festival', "Peppa's Jerk Chicken", 'snacks', '1 piece', 180, 3, 28, 6, 140, ['jamaican', 'festival']),
  item('peppas-rice-peas', 'Rice & Peas', "Peppa's Jerk Chicken", 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('peppas-white-rice', 'White Rice', "Peppa's Jerk Chicken", 'snacks', '1 side', 280, 5, 58, 3, 420, ['jamaican', 'rice']),
  item('peppas-macaroni-salad', 'Macaroni Salad', "Peppa's Jerk Chicken", 'snacks', '1 side', 320, 6, 36, 16, 580, ['jamaican', 'macaroni']),
  item('peppas-chicken-soup', 'Chicken Soup', "Peppa's Jerk Chicken", 'lunch', '1 bowl', 280, 16, 24, 12, 980, ['jamaican', 'soup']),
  item('peppas-jerk-pasta', 'Jerk Chicken & Peppas Pasta', "Peppa's Jerk Chicken", 'dinner', '1 plate', 980, 48, 92, 42, 1900, ['jamaican', 'jerk', 'pasta']),

  // Chef Creole — Miami Haitian / Caribbean (multi-location; calibrated estimates)
  item('chef-creole-griot', 'Griot (fried pork) with rice & plantains', 'Chef Creole', 'dinner', '1 plate', 920, 42, 78, 46, 1400, ['haitian', 'griot', 'caribbean', 'miami']),
  item('chef-creole-oxtail', 'Oxtail with rice & beans', 'Chef Creole', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['haitian', 'oxtail', 'caribbean']),
  item('chef-creole-stew-chicken', 'Stew Chicken with rice & beans', 'Chef Creole', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['haitian', 'stew', 'caribbean']),
  item('chef-creole-fish-filet', 'Fish Filet plate', 'Chef Creole', 'dinner', '1 plate', 680, 38, 52, 30, 1400, ['haitian', 'fish', 'caribbean']),
  item('chef-creole-fried-fish', 'Whole Fried Fish', 'Chef Creole', 'dinner', '1 fish', 820, 48, 28, 48, 1600, ['haitian', 'fish', 'caribbean']),
  item('chef-creole-fried-wings', 'Fried Wings', 'Chef Creole', 'lunch', '1 order', 520, 38, 8, 36, 1420, ['haitian', 'wings', 'caribbean']),
  item('chef-creole-jerk-wings', 'Jerk Wings', 'Chef Creole', 'lunch', '1 order', 540, 38, 10, 36, 1500, ['haitian', 'jerk', 'wings']),
  item('chef-creole-creole-wings', 'Creole Wings', 'Chef Creole', 'lunch', '1 order', 540, 38, 10, 36, 1520, ['haitian', 'creole', 'wings']),
  item('chef-creole-lemon-pepper-wings', 'Lemon Pepper Wings', 'Chef Creole', 'lunch', '1 order', 530, 38, 8, 36, 1480, ['haitian', 'wings']),
  item('chef-creole-creole-shrimp', 'Creole Shrimp plate', 'Chef Creole', 'dinner', '1 plate', 620, 36, 48, 28, 1680, ['haitian', 'shrimp', 'creole']),
  item('chef-creole-fried-shrimp', 'Fried Shrimp plate', 'Chef Creole', 'dinner', '1 plate', 680, 32, 52, 36, 1700, ['haitian', 'shrimp']),
  item('chef-creole-steamed-shrimp', 'Steamed Shrimp plate', 'Chef Creole', 'dinner', '1 plate', 420, 42, 18, 16, 1400, ['haitian', 'shrimp']),
  item('chef-creole-grilled-chicken', 'Grilled Chicken with rice & beans', 'Chef Creole', 'dinner', '1 plate', 620, 48, 58, 20, 1320, ['haitian', 'chicken']),
  item('chef-creole-fried-conch', 'Fried Conch', 'Chef Creole', 'dinner', '1 plate', 720, 36, 48, 38, 1600, ['haitian', 'conch', 'caribbean']),
  item('chef-creole-stew-conch', 'Stew Conch', 'Chef Creole', 'dinner', '1 plate', 640, 38, 42, 28, 1680, ['haitian', 'conch']),
  item('chef-creole-rice-beans', 'Rice & Red Beans', 'Chef Creole', 'snacks', '1 side', 340, 9, 58, 7, 620, ['haitian', 'diri', 'rice']),
  item('chef-creole-rice-peas', 'Rice & Sweet Peas', 'Chef Creole', 'snacks', '1 side', 340, 8, 58, 8, 600, ['haitian', 'rice and peas']),
  item('chef-creole-plantains', 'Sweet Plantains', 'Chef Creole', 'snacks', '1 side', 220, 1, 38, 8, 10, ['haitian', 'plantains', 'maduros']),
  item('chef-creole-pikliz', 'Pikliz', 'Chef Creole', 'snacks', '1 side', 40, 1, 8, 0, 280, ['haitian', 'pikliz', 'slaw']),
  item('chef-creole-legume', 'Legume (vegetable stew)', 'Chef Creole', 'dinner', '1 plate', 420, 12, 48, 18, 980, ['haitian', 'legim', 'legume']),

  // True Island Grille — Orlando Jamaican (menu from delivery listings; macros ≈ Golden Krust)
  item('true-island-beef-patty', 'Beef Jamaican Patty', 'True Island Grille', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'caribbean', 'patty', 'true island']),
  item('true-island-chicken-patty', 'Chicken Jamaican Patty', 'True Island Grille', 'lunch', '1 patty', 380, 12, 42, 18, 700, ['jamaican', 'patty']),
  item('true-island-jerk-chicken', 'Jerk Chicken (with rice & peas)', 'True Island Grille', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'caribbean']),
  item('true-island-jerk-pork', 'Jerk Pork (with rice & peas)', 'True Island Grille', 'dinner', '1 plate', 980, 48, 90, 42, 2000, ['jamaican', 'jerk', 'pork']),
  item('true-island-curry-chicken', 'Curry Chicken', 'True Island Grille', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('true-island-curry-goat', 'Curry Goat', 'True Island Grille', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('true-island-oxtail', 'Oxtail (with rice & peas)', 'True Island Grille', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('true-island-rasta-pasta', 'Signature Rasta Pasta', 'True Island Grille', 'dinner', '1 plate', 980, 42, 98, 42, 1900, ['jamaican', 'rasta pasta', 'pasta']),
  item('true-island-oxtail-rasta', 'Oxtail Rasta Pasta', 'True Island Grille', 'dinner', '1 plate', 1180, 48, 100, 52, 2100, ['jamaican', 'oxtail', 'pasta']),
  item('true-island-snapper', 'Whole Snapper Fish', 'True Island Grille', 'dinner', '1 fish', 820, 48, 28, 48, 1600, ['jamaican', 'fish', 'snapper']),
  item('true-island-escovitch', 'Escovitch Fish', 'True Island Grille', 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'escovitch', 'fish']),
  item('true-island-pepper-shrimp', 'Jamaican Style Pepper Shrimp', 'True Island Grille', 'lunch', '1 order', 420, 36, 12, 22, 1680, ['jamaican', 'shrimp', 'pepper']),
  item('true-island-jerk-wings', 'Jerk Wings', 'True Island Grille', 'snacks', '1 order', 780, 48, 12, 56, 2640, ['jamaican', 'jerk', 'wings']),
  item('true-island-fried-chicken', 'Yardstyle Fried Chicken', 'True Island Grille', 'dinner', '1 plate', 920, 46, 78, 48, 2000, ['jamaican', 'fried chicken']),
  item('true-island-pepper-steak', 'Jamaican Style Pepper Steak', 'True Island Grille', 'dinner', '1 plate', 780, 42, 62, 36, 1800, ['jamaican', 'steak']),
  item('true-island-coconut-shrimp', 'Coconut Shrimp', 'True Island Grille', 'snacks', '1 order', 610, 22, 52, 34, 980, ['jamaican', 'shrimp', 'coconut']),
  item('true-island-festival', 'Festival', 'True Island Grille', 'snacks', '1 piece', 180, 3, 28, 6, 140, ['jamaican', 'festival']),
  item('true-island-plantains', 'Sweet Plantains', 'True Island Grille', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),

  // Taste of Jamaica — common independent Jamaican name across TX/GA/USA (typical dinner + patty menu)
  item('taste-jamaica-beef-patty', 'Beef Patty', 'Taste of Jamaica', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'caribbean', 'patty', 'taste of jamaica']),
  item('taste-jamaica-chicken-patty', 'Chicken Patty', 'Taste of Jamaica', 'lunch', '1 patty', 380, 12, 42, 18, 700, ['jamaican', 'patty']),
  item('taste-jamaica-veggie-patty', 'Vegetable Patty', 'Taste of Jamaica', 'lunch', '1 patty', 260, 6, 30, 12, 540, ['jamaican', 'vegetarian', 'patty']),
  item('taste-jamaica-jerk-chicken', 'Jerk Chicken Dinner (rice & peas, cabbage)', 'Taste of Jamaica', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'caribbean']),
  item('taste-jamaica-curry-chicken', 'Curry Chicken Dinner (rice & peas, cabbage)', 'Taste of Jamaica', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('taste-jamaica-stew-chicken', 'Stew Chicken Dinner (rice & peas, cabbage)', 'Taste of Jamaica', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('taste-jamaica-oxtail', 'Oxtail Dinner (rice & peas, cabbage)', 'Taste of Jamaica', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('taste-jamaica-curry-goat', 'Curry Goat Dinner (rice & peas, cabbage)', 'Taste of Jamaica', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('taste-jamaica-jerk-shrimp', 'Jerk Shrimp Dinner', 'Taste of Jamaica', 'dinner', '1 plate', 700, 38, 56, 30, 1680, ['jamaican', 'jerk', 'shrimp']),
  item('taste-jamaica-curry-shrimp', 'Curry Shrimp Dinner', 'Taste of Jamaica', 'dinner', '1 plate', 680, 36, 58, 28, 1700, ['jamaican', 'curry', 'shrimp']),
  item('taste-jamaica-jerk-pork-ribs', 'Jerk Pork Ribs Dinner', 'Taste of Jamaica', 'dinner', '1 plate', 1100, 52, 78, 62, 2200, ['jamaican', 'jerk', 'ribs', 'pork']),
  item('taste-jamaica-brown-stew-fish', 'Brown Stew Fish', 'Taste of Jamaica', 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'fish', 'stew']),
  item('taste-jamaica-fried-shrimp', '8 Piece Shrimp Dinner (fried)', 'Taste of Jamaica', 'dinner', '1 plate', 920, 36, 78, 48, 1900, ['jamaican', 'shrimp', 'fried']),
  item('taste-jamaica-coco-bread', 'Coco Bread', 'Taste of Jamaica', 'snacks', '1 piece', 400, 8, 58, 15, 470, ['jamaican', 'coco bread']),
  item('taste-jamaica-patty-coco', 'Beef Patty in Coco Bread', 'Taste of Jamaica', 'lunch', '1 sandwich', 830, 20, 101, 38, 1160, ['jamaican', 'patty', 'coco bread']),
  item('taste-jamaica-rice-peas', 'Rice & Peas', 'Taste of Jamaica', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('taste-jamaica-cabbage', 'Steamed Cabbage', 'Taste of Jamaica', 'snacks', '1 side', 80, 3, 10, 3, 280, ['jamaican', 'cabbage']),

  // Caribbean Sunshine Bakery — Orlando multi-location (patties + dinner; published menu, macros ≈ Golden Krust)
  item('csb-beef-patty', 'Beef Patty (regular)', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'caribbean', 'patty', 'sunshine bakery']),
  item('csb-spicy-beef-patty', 'Spicy Beef Patty', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 440, 12, 43, 24, 720, ['jamaican', 'patty', 'spicy']),
  item('csb-chicken-patty', 'Chicken Patty', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 380, 12, 42, 18, 700, ['jamaican', 'patty']),
  item('csb-fish-patty', 'Fish Patty', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 360, 11, 40, 18, 620, ['jamaican', 'patty', 'fish']),
  item('csb-veggie-patty', 'Veggie Patty', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 260, 6, 30, 12, 540, ['jamaican', 'vegetarian', 'patty']),
  item('csb-callaloo-patty', 'Callaloo Patty', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 340, 12, 36, 16, 780, ['jamaican', 'callaloo', 'patty']),
  item('csb-oxtail-patty', 'Oxtail Patty', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 480, 16, 42, 26, 820, ['jamaican', 'oxtail', 'patty']),
  item('csb-ackee-patty', 'Ackee & Saltfish Patty', 'Caribbean Sunshine Bakery', 'lunch', '1 patty', 400, 14, 38, 20, 880, ['jamaican', 'ackee', 'patty']),
  item('csb-coco-bread', 'Coco Bread', 'Caribbean Sunshine Bakery', 'snacks', '1 piece', 400, 8, 58, 15, 470, ['jamaican', 'coco bread']),
  item('csb-patty-coco', 'Patty and Coco Bread (combo)', 'Caribbean Sunshine Bakery', 'lunch', '1 combo', 830, 20, 101, 38, 1160, ['jamaican', 'patty', 'coco bread']),
  item('csb-jerk-chicken', 'Jerk Chicken Dinner (rice, plantain, cabbage)', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 980, 50, 105, 38, 2000, ['jamaican', 'jerk', 'caribbean']),
  item('csb-fried-chicken', 'Fried Chicken Dinner', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 1020, 48, 98, 48, 2100, ['jamaican', 'fried chicken']),
  item('csb-curry-chicken', 'Curry Chicken Dinner', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 720, 36, 78, 26, 1600, ['jamaican', 'curry']),
  item('csb-brown-stew', 'Brown Stew Chicken Dinner', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 760, 38, 78, 30, 1680, ['jamaican', 'stew']),
  item('csb-oxtail', 'Oxtail Dinner (small)', 'Caribbean Sunshine Bakery', 'dinner', '1 small plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('csb-curry-goat', 'Curry Goat Dinner', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 920, 46, 95, 36, 1800, ['jamaican', 'curry', 'goat']),
  item('csb-stew-beef', 'Stew Beef Dinner', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 880, 44, 82, 38, 1760, ['jamaican', 'beef', 'stew']),
  item('csb-jerk-pork', 'Jerk Pork Dinner', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 980, 48, 90, 42, 2000, ['jamaican', 'jerk', 'pork']),
  item('csb-escovitch', 'Escovitch Red Snapper', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 780, 42, 62, 36, 1700, ['jamaican', 'escovitch', 'snapper']),
  item('csb-curry-shrimp', 'Curry Shrimp', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 720, 38, 68, 28, 1780, ['jamaican', 'curry', 'shrimp']),
  item('csb-coconut-shrimp', 'Coconut Shrimp Dinner', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 980, 32, 92, 48, 1900, ['jamaican', 'shrimp', 'coconut']),
  item('csb-tropical-salmon', 'Tropical Salmon', 'Caribbean Sunshine Bakery', 'dinner', '1 plate', 840, 48, 62, 38, 1650, ['jamaican', 'salmon']),
  item('csb-jerk-salad', 'Jerk Chicken Salad', 'Caribbean Sunshine Bakery', 'lunch', '1 salad', 520, 44, 18, 28, 1400, ['jamaican', 'jerk', 'salad']),
  item('csb-chicken-soup', 'Chicken Soup (bowl)', 'Caribbean Sunshine Bakery', 'lunch', '1 bowl', 280, 16, 24, 12, 980, ['jamaican', 'soup']),
  item('csb-red-peas-soup', 'Red Peas Soup (bowl)', 'Caribbean Sunshine Bakery', 'lunch', '1 bowl', 320, 14, 36, 12, 1100, ['jamaican', 'soup', 'peas']),
  item('csb-spiced-bun', 'Jamaican Spiced Bun (slice)', 'Caribbean Sunshine Bakery', 'snacks', '1 slice', 210, 5, 37, 3, 65, ['jamaican', 'bun', 'dessert']),
  item('csb-rum-cake', 'Rum (Black) Cake', 'Caribbean Sunshine Bakery', 'snacks', '1 slice', 380, 4, 52, 16, 180, ['jamaican', 'rum cake', 'dessert']),

  // Miss Lily's — NYC modern Jamaican (signature menu; macros ≈ Golden Krust / Bahama Breeze plates)
  item('miss-lilys-jerk-chicken', "World Famous Jerk Chicken (½ chicken, rice & peas)", "Miss Lily's", 'dinner', '1 plate', 980, 58, 88, 42, 2100, ['jamaican', 'jerk', 'caribbean', 'miss lilys']),
  item('miss-lilys-oxtail', 'Classic Jamaican Oxtail Stew (rice & peas)', "Miss Lily's", 'dinner', '1 plate', 1100, 54, 92, 54, 1800, ['jamaican', 'oxtail']),
  item('miss-lilys-jerk-ribs', 'Jerk Pork Spare Ribs', "Miss Lily's", 'dinner', '1 plate', 1200, 56, 78, 68, 2400, ['jamaican', 'jerk', 'ribs', 'pork']),
  item('miss-lilys-escovitch', 'Hellshire Beach Fried Whole Fish (escovitch)', "Miss Lily's", 'dinner', '1 fish', 860, 50, 42, 48, 1800, ['jamaican', 'escovitch', 'fish']),
  item('miss-lilys-ackee', 'Ackee & Saltfish (plantains, greens, festival)', "Miss Lily's", 'breakfast', '1 plate', 720, 28, 68, 36, 1680, ['jamaican', 'ackee', 'saltfish']),
  item('miss-lilys-jerk-roti', 'Jerk Chicken Roti', "Miss Lily's", 'lunch', '1 roti', 780, 42, 78, 32, 1700, ['jamaican', 'jerk', 'roti']),
  item('miss-lilys-veg-roti', 'West Indian Curry Vegetable Roti', "Miss Lily's", 'lunch', '1 roti', 620, 16, 88, 22, 1400, ['jamaican', 'roti', 'vegetarian', 'curry']),
  item('miss-lilys-jerk-wings', 'Jerk Wings', "Miss Lily's", 'snacks', '1 order', 780, 48, 12, 56, 2640, ['jamaican', 'jerk', 'wings']),
  item('miss-lilys-pepper-shrimp', 'Hot Pepper Shrimp', "Miss Lily's", 'snacks', '1 order', 420, 36, 12, 22, 1680, ['jamaican', 'shrimp', 'pepper']),
  item('miss-lilys-cod-fritters', 'Cod Fish Fritters', "Miss Lily's", 'snacks', '1 order', 480, 22, 42, 24, 1200, ['jamaican', 'fritters', 'cod']),
  item('miss-lilys-oxtail-roll', 'Crispy Oxtail Spring Roll', "Miss Lily's", 'snacks', '1 order', 520, 22, 38, 28, 1100, ['jamaican', 'oxtail', 'appetizer']),
  item('miss-lilys-jerk-sandwich', 'Jerk Chicken Sandwich (coco bread)', "Miss Lily's", 'sandwiches', '1 sandwich', 860, 46, 72, 38, 1900, ['jamaican', 'jerk', 'sandwich']),
  item('miss-lilys-patty-melt', 'Jamaican Patty Melt', "Miss Lily's", 'sandwiches', '1 sandwich', 920, 38, 68, 48, 1800, ['jamaican', 'patty', 'melt']),
  item('miss-lilys-jerk-caesar', 'Jerk Chicken Caesar Salad', "Miss Lily's", 'lunch', '1 salad', 680, 42, 28, 42, 1500, ['jamaican', 'jerk', 'salad', 'caesar']),
  item('miss-lilys-plantains', 'Sweet Plantains', "Miss Lily's", 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),
  item('miss-lilys-rice-peas', 'Rice & Peas', "Miss Lily's", 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('miss-lilys-jerk-fries', 'Jerk Fries', "Miss Lily's", 'snacks', '1 side', 420, 5, 52, 22, 780, ['jamaican', 'fries', 'jerk']),
  item('miss-lilys-banana-pudding', "Miss Lily's Banana Pudding", "Miss Lily's", 'snacks', '1 serving', 380, 6, 58, 14, 220, ['jamaican', 'dessert', 'pudding']),

  // Jerk at Nite — DC / Baltimore / Detroit / Houston (multi-city; typical delivery menu)
  item('jan-di-yaddie', "Di Yaddie (smoked jerk chicken, rice & peas, cabbage)", 'Jerk at Nite', 'dinner', '1 plate', 920, 50, 95, 34, 1900, ['jamaican', 'jerk', 'caribbean', 'jerk at nite']),
  item('jan-jerk-box', 'Jerk Box (jerk chicken, JaMac & cheese, rasta bread)', 'Jerk at Nite', 'dinner', '1 box', 1100, 48, 98, 52, 2200, ['jamaican', 'jerk', 'mac']),
  item('jan-oxtail', 'Oxtail (rice & peas, cabbage, plantains)', 'Jerk at Nite', 'dinner', '1 plate', 1120, 54, 98, 54, 1800, ['jamaican', 'oxtail']),
  item('jan-rasta-pasta', 'Alfredo Rasta Pasta', 'Jerk at Nite', 'dinner', '1 plate', 980, 32, 98, 48, 1900, ['jamaican', 'rasta pasta', 'pasta']),
  item('jan-rasta-chicken', 'Rasta Pasta with Jerk Chicken', 'Jerk at Nite', 'dinner', '1 plate', 1180, 52, 100, 52, 2100, ['jamaican', 'rasta pasta', 'jerk']),
  item('jan-rasta-salmon', 'Rasta Pasta with Salmon', 'Jerk at Nite', 'dinner', '1 plate', 1120, 48, 96, 48, 2000, ['jamaican', 'rasta pasta', 'salmon']),
  item('jan-kingston-kurry', 'Kingston Kurry (curry dinner with rice)', 'Jerk at Nite', 'dinner', '1 plate', 720, 36, 78, 26, 1600, ['jamaican', 'curry']),
  item('jan-jerk-wings', 'Jerk Wings', 'Jerk at Nite', 'snacks', '1 order', 780, 48, 12, 56, 2640, ['jamaican', 'jerk', 'wings']),
  item('jan-jerk-tacos', 'Jerk Tacos (3)', 'Jerk at Nite', 'lunch', '3 tacos', 720, 36, 58, 34, 1600, ['jamaican', 'jerk', 'tacos']),
  item('jan-rasta-monsta', 'The Rasta Monsta (oxtail, mac, beef patty in coco bread)', 'Jerk at Nite', 'sandwiches', '1 sandwich', 1400, 58, 120, 68, 2600, ['jamaican', 'oxtail', 'sandwich', 'monsta']),
  item('jan-beef-patty', 'Beef Patty', 'Jerk at Nite', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('jan-plantains', 'Sweet Plantains', 'Jerk at Nite', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),
  item('jan-jamac', "JaMac & Cheese", 'Jerk at Nite', 'snacks', '1 side', 420, 14, 36, 24, 880, ['jamaican', 'mac']),
  item('jan-cabbage', 'Seasoned Cabbage', 'Jerk at Nite', 'snacks', '1 side', 80, 3, 10, 3, 280, ['jamaican', 'cabbage']),
  item('jan-rice-peas', 'Rice & Peas', 'Jerk at Nite', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),

  // Jerk King — Midwest US (Mall of America / Rochester) + Caribbean grill franchise menu
  item('jerk-king-jerk-chicken', 'Jerk Chicken Meal (rice & peas)', 'Jerk King', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'caribbean', 'jerk king']),
  item('jerk-king-jerk-boneless', 'Jerk Chicken Boneless Meal', 'Jerk King', 'dinner', '1 plate', 860, 52, 90, 30, 1800, ['jamaican', 'jerk']),
  item('jerk-king-curry-chicken', 'Curry Chicken Meal', 'Jerk King', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('jerk-king-stew-chicken', 'Stew Chicken Meal', 'Jerk King', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('jerk-king-curry-goat', 'Curry Goat Meal', 'Jerk King', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('jerk-king-oxtail', 'Oxtail Meal', 'Jerk King', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('jerk-king-stew-beef', 'Stew Beef Meal', 'Jerk King', 'dinner', '1 plate', 880, 44, 82, 38, 1760, ['jamaican', 'beef', 'stew']),
  item('jerk-king-fried-chicken', 'Fried Chicken with Fries', 'Jerk King', 'dinner', '1 plate', 980, 42, 78, 52, 2000, ['jamaican', 'fried chicken']),
  item('jerk-king-chicken-roti', 'Chicken Roti', 'Jerk King', 'lunch', '1 roti', 620, 36, 60, 22, 1100, ['jamaican', 'roti', 'trinidad']),
  item('jerk-king-goat-roti', 'Goat Roti', 'Jerk King', 'dinner', '1 roti', 680, 34, 62, 28, 1200, ['jamaican', 'roti', 'goat']),
  item('jerk-king-jerk-roti', 'Jerk Chicken Roti', 'Jerk King', 'lunch', '1 roti', 700, 40, 62, 28, 1400, ['jamaican', 'jerk', 'roti']),
  item('jerk-king-veggie-roti', 'Vegetarian Roti', 'Jerk King', 'lunch', '1 roti', 540, 14, 72, 18, 980, ['jamaican', 'roti', 'vegetarian']),
  item('jerk-king-patty', 'Jamaican Patty', 'Jerk King', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('jerk-king-plantain', 'Fried Plantain', 'Jerk King', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),
  item('jerk-king-dumpling', 'Fried Dumpling', 'Jerk King', 'snacks', '1 piece', 180, 3, 28, 6, 140, ['jamaican', 'dumpling']),

  // Ja' Grill — Chicago (Hyde Park signature Jamaican)
  item('ja-grill-jerk-chicken', 'Jerk Chicken (½ chicken, rice & peas, plantains)', "Ja' Grill", 'dinner', '1 plate', 980, 56, 95, 38, 2000, ['jamaican', 'jerk', 'chicago', 'ja grill']),
  item('ja-grill-jerk-pork', 'Jerk Pork Dinner', "Ja' Grill", 'dinner', '1 plate', 980, 48, 90, 42, 2000, ['jamaican', 'jerk', 'pork']),
  item('ja-grill-curry-chicken', 'Curry Chicken Dinner', "Ja' Grill", 'dinner', '1 plate', 720, 36, 78, 26, 1600, ['jamaican', 'curry']),
  item('ja-grill-curry-goat', 'Curry Goat Dinner', "Ja' Grill", 'dinner', '1 plate', 920, 48, 92, 38, 1800, ['jamaican', 'curry', 'goat']),
  item('ja-grill-oxtail', 'Ox Tail Dinner (butter beans)', "Ja' Grill", 'dinner', '1 plate', 1150, 54, 95, 56, 1900, ['jamaican', 'oxtail']),
  item('ja-grill-stew-chicken', 'Stew Chicken Dinner', "Ja' Grill", 'dinner', '1 plate', 720, 38, 78, 28, 1600, ['jamaican', 'stew']),
  item('ja-grill-escovitch', 'Whole Red Snapper Escoveitch', "Ja' Grill", 'dinner', '1 fish', 860, 50, 42, 48, 1800, ['jamaican', 'escovitch', 'snapper']),
  item('ja-grill-jerk-shrimp', 'Jerk Shrimp Dinner', "Ja' Grill", 'dinner', '1 plate', 700, 38, 56, 30, 1680, ['jamaican', 'jerk', 'shrimp']),
  item('ja-grill-jerk-wings', 'Jerk Wings', "Ja' Grill", 'snacks', '1 order', 780, 48, 12, 56, 2640, ['jamaican', 'jerk', 'wings']),
  item('ja-grill-honey-wings', 'Honey Wings', "Ja' Grill", 'snacks', '1 order', 820, 46, 28, 52, 2400, ['jamaican', 'wings', 'honey']),
  item('ja-grill-jerk-taco', 'Jerk Chicken Taco', "Ja' Grill", 'lunch', '1 taco', 320, 18, 28, 14, 720, ['jamaican', 'jerk', 'taco']),
  item('ja-grill-jerk-salad', 'Jerk Chicken Salad', "Ja' Grill", 'lunch', '1 salad', 520, 44, 18, 28, 1400, ['jamaican', 'jerk', 'salad']),
  item('ja-grill-beef-patty', 'Beef Patty', "Ja' Grill", 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('ja-grill-ital-stew', 'Vegan Ital Stew', "Ja' Grill", 'dinner', '1 plate', 480, 14, 68, 16, 980, ['jamaican', 'ital', 'vegan', 'vegetarian']),
  item('ja-grill-plantains', 'Sweet Plantains', "Ja' Grill", 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),
  item('ja-grill-rum-cake', 'Rum Cake', "Ja' Grill", 'snacks', '1 slice', 380, 4, 52, 16, 180, ['jamaican', 'rum cake', 'dessert']),

  // The Jerk Shack — San Antonio (Chef Nicola Blaque; published menu)
  item('jerk-shack-beef-patty', 'Beef Patty', 'The Jerk Shack', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'caribbean', 'patty', 'jerk shack', 'san antonio']),
  item('jerk-shack-jerk-chicken-3', 'Jerk Chicken (3 pc)', 'The Jerk Shack', 'lunch', '3 pieces', 520, 42, 4, 34, 1400, ['jamaican', 'jerk']),
  item('jerk-shack-jerk-plate', '3 Piece Jerk Chicken Plate (2 sides)', 'The Jerk Shack', 'dinner', '1 plate', 920, 50, 78, 42, 2000, ['jamaican', 'jerk']),
  item('jerk-shack-fried-plate', '3 Piece Fried Chicken Plate', 'The Jerk Shack', 'dinner', '1 plate', 980, 46, 78, 52, 2100, ['jamaican', 'fried chicken']),
  item('jerk-shack-mix-plate', 'Mix Chicken Plate (jerk + fried)', 'The Jerk Shack', 'dinner', '1 plate', 1020, 52, 78, 52, 2200, ['jamaican', 'jerk', 'fried']),
  item('jerk-shack-curry-chicken', 'Curry Chicken (rice & peas, cabbage)', 'The Jerk Shack', 'dinner', '1 plate', 780, 42, 78, 32, 1700, ['jamaican', 'curry']),
  item('jerk-shack-curry-shrimp', 'Curry Shrimp (rice & peas, cabbage, plantains)', 'The Jerk Shack', 'dinner', '1 plate', 820, 40, 82, 34, 1800, ['jamaican', 'curry', 'shrimp']),
  item('jerk-shack-oxtail', 'Oxtail Plate (cabbage, rice & peas, plantains)', 'The Jerk Shack', 'dinner', '1 plate', 1150, 54, 98, 56, 1900, ['jamaican', 'oxtail']),
  item('jerk-shack-rasta-pasta', 'Rasta Pasta (jerk Alfredo)', 'The Jerk Shack', 'dinner', '1 plate', 980, 32, 98, 48, 1900, ['jamaican', 'rasta pasta']),
  item('jerk-shack-chopped-sandwich', 'Chopped Jerk Chicken Sandwich', 'The Jerk Shack', 'sandwiches', '1 sandwich', 780, 42, 68, 36, 1800, ['jamaican', 'jerk', 'sandwich']),
  item('jerk-shack-chopped-tacos', '3 Chopped Jerk Tacos', 'The Jerk Shack', 'lunch', '3 tacos', 720, 36, 58, 34, 1600, ['jamaican', 'jerk', 'tacos']),
  item('jerk-shack-sticky', 'Sticky Chicken (3 pc with side)', 'The Jerk Shack', 'dinner', '1 plate', 920, 44, 72, 48, 2000, ['jamaican', 'sticky', 'chicken']),
  item('jerk-shack-wings-7', '7pc Wing Meal (2 sides)', 'The Jerk Shack', 'dinner', '1 meal', 980, 48, 62, 56, 2400, ['jamaican', 'wings']),
  item('jerk-shack-plantains', 'Fried Plantains', 'The Jerk Shack', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),
  item('jerk-shack-masala-fries', 'Masala Fries', 'The Jerk Shack', 'snacks', '1 side', 420, 5, 52, 22, 780, ['jamaican', 'fries', 'masala']),
  item('jerk-shack-mac', 'Mac N Cheese', 'The Jerk Shack', 'snacks', '1 side', 420, 14, 36, 24, 880, ['jamaican', 'mac']),
  item('jerk-shack-banana-pudding', 'Banana Pudding', 'The Jerk Shack', 'snacks', '1 serving', 380, 6, 58, 14, 220, ['jamaican', 'dessert', 'pudding']),

  // Jamaican Jerk Biz — Atlanta metro (Mableton / Atlanta)
  item('jjb-jerk-chicken', 'Jerk Chicken Dinner', 'Jamaican Jerk Biz', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'atlanta', 'jerk biz']),
  item('jjb-jerk-salmon', 'Jerk Salmon Dinner', 'Jamaican Jerk Biz', 'dinner', '1 plate', 780, 44, 58, 36, 1500, ['jamaican', 'jerk', 'salmon']),
  item('jjb-jerk-shrimp', 'Jerk Shrimp Dinner', 'Jamaican Jerk Biz', 'dinner', '1 plate', 700, 38, 56, 30, 1680, ['jamaican', 'jerk', 'shrimp']),
  item('jjb-stew-chicken', 'Stew Chicken Dinner', 'Jamaican Jerk Biz', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('jjb-pineapple-chicken', 'Pineapple Chicken', 'Jamaican Jerk Biz', 'dinner', '1 plate', 820, 46, 88, 28, 1700, ['jamaican', 'pineapple', 'chicken']),
  item('jjb-lamb-chops', 'Lamb Chops Dinner', 'Jamaican Jerk Biz', 'dinner', '1 plate', 980, 52, 62, 52, 1800, ['jamaican', 'lamb']),
  item('jjb-oxtail', 'Oxtail Dinner', 'Jamaican Jerk Biz', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('jjb-curry-goat', 'Curry Goat Dinner', 'Jamaican Jerk Biz', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('jjb-yellow-rice', 'Yellow Rice', 'Jamaican Jerk Biz', 'snacks', '1 side', 280, 5, 54, 4, 480, ['jamaican', 'rice']),
  item('jjb-cabbage', 'Steam Cabbage', 'Jamaican Jerk Biz', 'snacks', '1 side', 80, 3, 10, 3, 280, ['jamaican', 'cabbage']),
  item('jjb-potato-salad', 'Potato Salad', 'Jamaican Jerk Biz', 'snacks', '1 side', 280, 4, 28, 16, 420, ['jamaican', 'potato salad']),

  // Mark's Jamaican Bar & Grill — Orlando (also searched as Mark's Jamaican Grille)
  item('marks-jerk-chicken', 'Jerk Chicken (rice & peas, cabbage, plantains)', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 980, 50, 105, 38, 2000, ['jamaican', 'jerk', 'marks', 'marks jamaican grille']),
  item('marks-brown-stew', 'Brown Stew Chicken', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 760, 38, 78, 30, 1680, ['jamaican', 'stew']),
  item('marks-curry-chicken', 'Curry Chicken', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 720, 36, 78, 26, 1600, ['jamaican', 'curry']),
  item('marks-curry-goat', 'Curry Goat', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 920, 46, 95, 36, 1800, ['jamaican', 'curry', 'goat']),
  item('marks-oxtail', 'Oxtail', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 1100, 54, 95, 54, 1800, ['jamaican', 'oxtail']),
  item('marks-jerk-pork', 'Jerk Pork', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 980, 48, 90, 42, 2000, ['jamaican', 'jerk', 'pork']),
  item('marks-jerk-shrimp', 'Jerk Shrimp', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 700, 38, 56, 30, 1680, ['jamaican', 'jerk', 'shrimp']),
  item('marks-rasta-pasta', 'Chicken Rasta Pasta', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 1100, 48, 98, 48, 2000, ['jamaican', 'rasta pasta']),
  item('marks-jerk-pork-fried-rice', 'Jerk Pork Fried Rice', "Mark's Jamaican Bar & Grill", 'dinner', '1 plate', 980, 42, 92, 42, 1900, ['jamaican', 'jerk', 'fried rice']),
  item('marks-curry-roti', 'Curry Chicken Roti', "Mark's Jamaican Bar & Grill", 'lunch', '1 roti', 680, 38, 68, 26, 1400, ['jamaican', 'roti', 'curry']),
  item('marks-beef-patty', 'Jamaican Beef Patty', "Mark's Jamaican Bar & Grill", 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('marks-wings', 'Chicken Wings (jerk)', "Mark's Jamaican Bar & Grill", 'snacks', '1 order', 820, 46, 28, 52, 2400, ['jamaican', 'wings', 'jerk']),
  item('marks-festival', 'Festival', "Mark's Jamaican Bar & Grill", 'snacks', '1 piece', 180, 3, 28, 6, 140, ['jamaican', 'festival']),
  item('marks-plantains', 'Fried Plantains', "Mark's Jamaican Bar & Grill", 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),

  // Negril Jamaican Restaurant — Orlando (Kirkman / Silver Star)
  item('negril-orl-jerk-chicken', 'Jerk Chicken', 'Negril Jamaican Restaurant', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'negril', 'orlando']),
  item('negril-orl-oxtail', 'Oxtail Jamaican Style', 'Negril Jamaican Restaurant', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail', 'negril']),
  item('negril-orl-curry-goat', 'Curry Goat', 'Negril Jamaican Restaurant', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('negril-orl-fried-chicken', 'Fried Chicken', 'Negril Jamaican Restaurant', 'dinner', '1 plate', 980, 46, 78, 52, 2100, ['jamaican', 'fried chicken']),
  item('negril-orl-ackee', 'Ackee & Saltfish', 'Negril Jamaican Restaurant', 'breakfast', '1 plate', 620, 22, 58, 32, 1480, ['jamaican', 'ackee', 'saltfish']),
  item('negril-orl-curry-chicken', 'Curry Chicken', 'Negril Jamaican Restaurant', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('negril-orl-brown-stew', 'Brown Stew Chicken', 'Negril Jamaican Restaurant', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('negril-orl-escovitch', 'Escovitch Fish', 'Negril Jamaican Restaurant', 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'escovitch', 'fish']),
  item('negril-orl-beef-patty', 'Beef Patty', 'Negril Jamaican Restaurant', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('negril-orl-coco-bread', 'Coco Bread', 'Negril Jamaican Restaurant', 'snacks', '1 piece', 400, 8, 58, 15, 470, ['jamaican', 'coco bread']),
  item('negril-orl-rice-peas', 'Rice & Peas', 'Negril Jamaican Restaurant', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('negril-orl-plantains', 'Sweet Plantains', 'Negril Jamaican Restaurant', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),

  // Negril Jamaican Eatery — DC / Silver Spring / Mitchellville / Laurel (since 1979; patties ship nationwide)
  item('negril-eats-jerk-chicken', 'Jerk Chicken (rice & peas, cabbage)', 'Negril Jamaican Eatery', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'negril eats', 'dmv']),
  item('negril-eats-oxtail', 'Oxtail (dumplings, lima beans)', 'Negril Jamaican Eatery', 'dinner', '1 plate', 1100, 54, 95, 54, 1800, ['jamaican', 'oxtail']),
  item('negril-eats-curry-chicken', 'Curried Chicken', 'Negril Jamaican Eatery', 'dinner', '1 plate', 720, 36, 78, 26, 1600, ['jamaican', 'curry']),
  item('negril-eats-fricassee', 'Fricassee (Brown Stew) Chicken', 'Negril Jamaican Eatery', 'dinner', '1 plate', 760, 38, 78, 30, 1680, ['jamaican', 'stew', 'fricassee']),
  item('negril-eats-curry-goat', 'Curried Goat', 'Negril Jamaican Eatery', 'dinner', '1 plate', 920, 46, 95, 36, 1800, ['jamaican', 'curry', 'goat']),
  item('negril-eats-jerk-drumettes', 'Jerk Drumettes (7) with rice & peas', 'Negril Jamaican Eatery', 'dinner', '1 plate', 980, 48, 78, 48, 2200, ['jamaican', 'jerk', 'wings']),
  item('negril-eats-escoveitch', 'Escoveitch Red Snapper', 'Negril Jamaican Eatery', 'dinner', '1 fish', 820, 48, 42, 42, 1700, ['jamaican', 'escovitch', 'snapper']),
  item('negril-eats-brown-stew-snapper', 'Brown Stew Red Snapper', 'Negril Jamaican Eatery', 'dinner', '1 fish', 840, 48, 48, 40, 1750, ['jamaican', 'snapper', 'stew']),
  item('negril-eats-curry-shrimp', 'Curried Shrimp', 'Negril Jamaican Eatery', 'dinner', '1 plate', 680, 36, 58, 28, 1700, ['jamaican', 'curry', 'shrimp']),
  item('negril-eats-chicken-roti', 'Chicken Roti', 'Negril Jamaican Eatery', 'lunch', '1 roti', 620, 36, 60, 22, 1100, ['jamaican', 'roti']),
  item('negril-eats-shrimp-roti', 'Curried Shrimp Roti', 'Negril Jamaican Eatery', 'lunch', '1 roti', 640, 32, 62, 24, 1200, ['jamaican', 'roti', 'shrimp']),
  item('negril-eats-veg-roti', 'Vegetable Roti', 'Negril Jamaican Eatery', 'lunch', '1 roti', 540, 14, 72, 18, 980, ['jamaican', 'roti', 'vegetarian']),
  item('negril-eats-beef-patty', 'Beef Patty (spicy)', 'Negril Jamaican Eatery', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('negril-eats-jerk-patty', 'Jerk Chicken Patty', 'Negril Jamaican Eatery', 'lunch', '1 patty', 400, 14, 40, 20, 720, ['jamaican', 'patty', 'jerk']),
  item('negril-eats-curry-patty', 'Curry Chicken Patty', 'Negril Jamaican Eatery', 'lunch', '1 patty', 380, 12, 42, 18, 700, ['jamaican', 'patty', 'curry']),
  item('negril-eats-jerk-sandwich', 'Jerk Chicken Sandwich (coco bread)', 'Negril Jamaican Eatery', 'sandwiches', '1 sandwich', 780, 42, 68, 32, 1700, ['jamaican', 'jerk', 'sandwich']),
  item('negril-eats-escoveitch-sandwich', 'Escoveitch Fish Sandwich (coco bread)', 'Negril Jamaican Eatery', 'sandwiches', '1 sandwich', 720, 36, 62, 32, 1600, ['jamaican', 'escovitch', 'sandwich']),
  item('negril-eats-coco-bread', 'Coco Bread', 'Negril Jamaican Eatery', 'snacks', '1 piece', 400, 8, 58, 15, 470, ['jamaican', 'coco bread']),
  item('negril-eats-rum-cake', 'Rum Cake', 'Negril Jamaican Eatery', 'snacks', '1 slice', 380, 4, 52, 16, 180, ['jamaican', 'rum cake', 'dessert']),
  item('negril-eats-chicken-soup', 'Chicken Soup', 'Negril Jamaican Eatery', 'lunch', '1 bowl', 320, 18, 32, 12, 1100, ['jamaican', 'soup']),

  // Scotch Bonnet Kitchen — Trenton / Lawrenceville NJ
  item('sbk-jerk-chicken', 'Jerk Chicken Dinner', 'Scotch Bonnet Kitchen', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'scotch bonnet', 'new jersey']),
  item('sbk-jerk-pork', 'Jerk Pork Dinner', 'Scotch Bonnet Kitchen', 'dinner', '1 plate', 980, 48, 90, 42, 2000, ['jamaican', 'jerk', 'pork']),
  item('sbk-oxtail', 'Oxtail Dinner', 'Scotch Bonnet Kitchen', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('sbk-brown-stew', 'Brown Stew Chicken', 'Scotch Bonnet Kitchen', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('sbk-curry-chicken', 'Curry Chicken', 'Scotch Bonnet Kitchen', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('sbk-escovitch', 'Escoveitch Fish', 'Scotch Bonnet Kitchen', 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'escovitch', 'fish']),
  item('sbk-curry-goat', 'Curry Goat', 'Scotch Bonnet Kitchen', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('sbk-rice-peas', 'Rice & Peas', 'Scotch Bonnet Kitchen', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('sbk-plantains', 'Fried Plantains', 'Scotch Bonnet Kitchen', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),
  item('sbk-mac', 'Mac and Cheese', 'Scotch Bonnet Kitchen', 'snacks', '1 side', 420, 14, 36, 24, 880, ['jamaican', 'mac']),

  // Reggae Pot Jamaican Grill — Colorado Springs (Mountain West coverage)
  item('reggae-pot-jerk-chicken', 'Jerk Chicken', 'Reggae Pot', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'colorado', 'reggae pot']),
  item('reggae-pot-oxtail', 'Stewed Oxtails', 'Reggae Pot', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('reggae-pot-curry-goat', 'Curried Goat', 'Reggae Pot', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('reggae-pot-curry-chicken', 'Curry Chicken', 'Reggae Pot', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('reggae-pot-escoveitch', 'Escoveitch Fish', 'Reggae Pot', 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'escovitch', 'fish']),
  item('reggae-pot-ackee', 'Ackee and Salt Fish', 'Reggae Pot', 'breakfast', '1 plate', 620, 22, 58, 32, 1480, ['jamaican', 'ackee']),
  item('reggae-pot-brown-stew', 'Brown Stew Chicken', 'Reggae Pot', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('reggae-pot-jerk-shrimp', 'Jerk Shrimp', 'Reggae Pot', 'dinner', '1 plate', 700, 38, 56, 30, 1680, ['jamaican', 'jerk', 'shrimp']),
  item('reggae-pot-rice-peas', 'Rice & Peas', 'Reggae Pot', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('reggae-pot-plantains', 'Sweet Plantains', 'Reggae Pot', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),

  // Island Spice — Edgewood / Baltimore area MD
  item('island-spice-jerk-chicken', 'Jerk Chicken Dinner', 'Island Spice', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'maryland', 'island spice']),
  item('island-spice-oxtail', 'Oxtail Dinner', 'Island Spice', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('island-spice-curry-goat', 'Curry Goat Dinner', 'Island Spice', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('island-spice-curry-chicken', 'Curry Chicken Dinner', 'Island Spice', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('island-spice-brown-stew', 'Brown Stew Chicken', 'Island Spice', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('island-spice-escovitch', 'Escovitch Fish', 'Island Spice', 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'escovitch']),
  item('island-spice-ital', 'Ital Vegetable Plate', 'Island Spice', 'dinner', '1 plate', 480, 14, 68, 16, 980, ['jamaican', 'ital', 'vegan']),
  item('island-spice-patty', 'Beef Patty', 'Island Spice', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('island-spice-rice-peas', 'Rice & Peas', 'Island Spice', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('island-spice-plantains', 'Fried Plantains', 'Island Spice', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),

  // Peppers Jamaican Belizean Kitchen — Los Angeles
  item('peppers-jerk-chicken', 'Island Fire Jerk Chicken', 'Peppers Jamaican', 'dinner', '1 plate', 920, 50, 95, 36, 1950, ['jamaican', 'jerk', 'los angeles', 'belizean']),
  item('peppers-oxtail', 'Joeline Signature Oxtails', 'Peppers Jamaican', 'dinner', '1 plate', 1100, 54, 95, 54, 1800, ['jamaican', 'oxtail']),
  item('peppers-curry-goat', 'Golden Pot Curry Goat', 'Peppers Jamaican', 'dinner', '1 plate', 920, 46, 95, 36, 1800, ['jamaican', 'curry', 'goat']),
  item('peppers-curry-chicken', 'Curry Chicken', 'Peppers Jamaican', 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('peppers-brown-stew', 'Brown Stew Chicken', 'Peppers Jamaican', 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('peppers-escovitch', 'Escovitch Fish', 'Peppers Jamaican', 'dinner', '1 plate', 720, 38, 58, 32, 1600, ['jamaican', 'escovitch']),
  item('peppers-rice-peas', 'Rice & Peas', 'Peppers Jamaican', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
  item('peppers-plantains', 'Sweet Plantains', 'Peppers Jamaican', 'snacks', '1 side', 220, 1, 38, 8, 10, ['jamaican', 'plantains']),

  // Bouka's Jamaican Restaurant — Mid-City Los Angeles
  item('boukas-jerk-chicken', 'Jerk Chicken', "Bouka's Jamaican Restaurant", 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk', 'los angeles', 'boukas']),
  item('boukas-oxtail', 'Oxtail', "Bouka's Jamaican Restaurant", 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail']),
  item('boukas-curry-goat', 'Curry Goat', "Bouka's Jamaican Restaurant", 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('boukas-rasta-pasta', 'Rasta Pasta', "Bouka's Jamaican Restaurant", 'dinner', '1 plate', 980, 32, 98, 48, 1900, ['jamaican', 'rasta pasta']),
  item('boukas-curry-chicken', 'Curry Chicken', "Bouka's Jamaican Restaurant", 'dinner', '1 plate', 640, 34, 62, 24, 1480, ['jamaican', 'curry']),
  item('boukas-brown-stew', 'Brown Stew Chicken', "Bouka's Jamaican Restaurant", 'dinner', '1 plate', 680, 36, 62, 28, 1540, ['jamaican', 'stew']),
  item('boukas-patty', 'Beef Patty', "Bouka's Jamaican Restaurant", 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('boukas-rice-peas', 'Rice & Peas', "Bouka's Jamaican Restaurant", 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),

  // Potwah Jamaican Cuisine — Crenshaw District LA
  item('potwah-oxtail', 'Oxtail (brown gravy)', 'Potwah Jamaican Cuisine', 'dinner', '1 plate', 1050, 52, 92, 52, 1600, ['jamaican', 'oxtail', 'los angeles', 'potwah']),
  item('potwah-jerk-chicken', 'Jerk Chicken', 'Potwah Jamaican Cuisine', 'dinner', '1 plate', 900, 50, 95, 34, 1900, ['jamaican', 'jerk']),
  item('potwah-curry-goat', 'Curry Goat', 'Potwah Jamaican Cuisine', 'dinner', '1 plate', 870, 46, 92, 34, 1700, ['jamaican', 'curry', 'goat']),
  item('potwah-brown-stew', 'Brown Stew Chicken (rice & peas, plantains)', 'Potwah Jamaican Cuisine', 'dinner', '1 plate', 760, 38, 88, 30, 1680, ['jamaican', 'stew']),
  item('potwah-ackee', 'Ackee & Saltfish', 'Potwah Jamaican Cuisine', 'breakfast', '1 plate', 620, 22, 58, 32, 1480, ['jamaican', 'ackee']),
  item('potwah-snapper', 'Red Snapper (brown stew)', 'Potwah Jamaican Cuisine', 'dinner', '1 fish', 840, 48, 48, 40, 1750, ['jamaican', 'snapper']),
  item('potwah-callaloo', 'Callaloo & Saltfish', 'Potwah Jamaican Cuisine', 'lunch', '1 plate', 480, 28, 32, 24, 1400, ['jamaican', 'callaloo']),
  item('potwah-patty', 'Golden Patty', 'Potwah Jamaican Cuisine', 'lunch', '1 patty', 430, 12, 43, 23, 690, ['jamaican', 'patty']),
  item('potwah-rice-peas', 'Rice & Peas', 'Potwah Jamaican Cuisine', 'snacks', '1 side', 340, 8, 58, 8, 620, ['jamaican', 'rice and peas']),
];
