import type { FastFoodCategory, FastFoodItem } from './fastFoodMenu';

/**
 * Steakhouse chains — casual + fine dining with published nutrition.
 * Saltgrass — menu calorie counts; macros Atwater-aligned (full PDF not published).
 * Ruth's Chris — 2026 dinner menu calories; macros Atwater-aligned (butter-finished steaks).
 * Fleming's — March 2026 nutrition PDF (full macros).
 * The Capital Grille — nutrition guide valid 8/24/26 (full macros).
 */
const item = (
  id: string,
  name: string,
  restaurant: string,
  category: FastFoodCategory,
  serving: string,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  sodium: number,
  keywords?: string[],
): FastFoodItem => ({ id, name, restaurant, category, serving, calories, protein, carbs, fat, sodium, ...(keywords ? { keywords } : {}) });

export const STEAKHOUSE_FAST_FOOD_ITEMS: FastFoodItem[] = [
  // Saltgrass Steak House — published menu calories; macros ≈ Atwater (steak-only unless noted)
  item('sg-sirloin-8', 'Wagon Boss Top Sirloin (8 oz)', 'Saltgrass Steak House', 'dinner', '8 oz', 540, 52, 2, 36, 980, ['steak', 'sirloin']),
  item('sg-sirloin-10', 'Wagon Boss Top Sirloin (10 oz)', 'Saltgrass Steak House', 'dinner', '10 oz', 730, 68, 2, 50, 1180, ['steak', 'sirloin']),
  item('sg-ribeye-12', "Pat's Ribeye (12 oz)", 'Saltgrass Steak House', 'dinner', '12 oz', 960, 72, 2, 74, 1280, ['steak', 'ribeye']),
  item('sg-ribeye-16', "Pat's Ribeye (16 oz)", 'Saltgrass Steak House', 'dinner', '16 oz', 1260, 92, 2, 98, 1580, ['steak', 'ribeye']),
  item('sg-filet-6', "Maudeen's Center-Cut Filet (6 oz)", 'Saltgrass Steak House', 'dinner', '6 oz', 550, 48, 2, 38, 820, ['steak', 'filet']),
  item('sg-filet-9', "Maudeen's Center-Cut Filet (9 oz)", 'Saltgrass Steak House', 'dinner', '9 oz', 760, 66, 2, 54, 980, ['steak', 'filet']),
  item('sg-ny-strip', 'New York Strip (12 oz)', 'Saltgrass Steak House', 'dinner', '12 oz', 820, 68, 2, 60, 1180, ['steak', 'strip']),
  item('sg-tbone', 'Texas T-Bone (17 oz)', 'Saltgrass Steak House', 'dinner', '17 oz', 1050, 88, 2, 76, 1420, ['steak', 'tbone']),
  item('sg-porterhouse', 'Silver Star Porterhouse (22 oz)', 'Saltgrass Steak House', 'dinner', '22 oz', 1520, 118, 2, 114, 1680, ['steak']),
  item('sg-bone-in-ribeye', 'Bone-In Ribeye (21 oz)', 'Saltgrass Steak House', 'dinner', '21 oz', 1490, 108, 2, 116, 1620, ['steak', 'ribeye']),
  item('sg-country-fried', 'Country Fried Steak', 'Saltgrass Steak House', 'dinner', '1 entrée', 930, 42, 58, 58, 2140, ['steak']),
  item('sg-chopped-steak', 'Chopped Steak', 'Saltgrass Steak House', 'dinner', '1 entrée', 790, 48, 12, 60, 1680, ['steak']),
  item('sg-ribs', 'BBQ Pork Ribs', 'Saltgrass Steak House', 'dinner', '1 order', 1110, 72, 48, 72, 2480, ['ribs', 'bbq']),
  item('sg-grilled-chicken', 'Grilled Chicken Breast', 'Saltgrass Steak House', 'dinner', '1 entrée', 560, 62, 8, 30, 1280, ['chicken']),
  item('sg-salmon', 'Atlantic Salmon', 'Saltgrass Steak House', 'dinner', '1 entrée', 480, 42, 4, 34, 720, ['salmon', 'fish']),
  item('sg-range-rattlers', 'Range Rattlers', 'Saltgrass Steak House', 'snacks', '1 appetizer', 930, 36, 48, 64, 1980, ['appetizer', 'shrimp']),
  item('sg-cheese-fries', 'Cheese Fries', 'Saltgrass Steak House', 'snacks', '1 appetizer', 1830, 48, 128, 122, 2860, ['fries']),
  item('sg-queso', 'Queso Fresco', 'Saltgrass Steak House', 'snacks', '1 appetizer', 1160, 32, 82, 78, 2420, ['queso', 'dip']),
  item('sg-fries', 'French Fries', 'Saltgrass Steak House', 'snacks', '1 side', 370, 4, 48, 18, 780, ['fries']),
  item('sg-mashed', 'Mashed Potatoes', 'Saltgrass Steak House', 'snacks', '1 side', 320, 6, 38, 16, 680, ['side']),
  item('sg-mac', 'Smoked Macaroni & Cheese', 'Saltgrass Steak House', 'snacks', '1 side', 440, 14, 38, 26, 980, ['mac', 'side']),
  item('sg-cheeseburger', 'Cheeseburger (with fries)', 'Saltgrass Steak House', 'sandwiches', '1 burger + fries', 830, 42, 58, 48, 1680, ['burger']),

  // Ruth's Chris Steak House — 2026 dinner menu calories; macros ≈ Atwater (sizzling butter)
  item('rc-filet-11', 'Filet (11 oz)', "Ruth's Chris Steak House", 'dinner', '11 oz', 500, 58, 2, 28, 720, ['steak', 'filet']),
  item('rc-petite-filet', 'Petite Filet (8 oz)', "Ruth's Chris Steak House", 'dinner', '8 oz', 340, 42, 1, 18, 580, ['steak', 'filet']),
  item('rc-ny-strip', 'New York Strip (16 oz)', "Ruth's Chris Steak House", 'dinner', '16 oz', 1390, 82, 2, 116, 980, ['steak', 'strip']),
  item('rc-ribeye', 'Ribeye (16 oz)', "Ruth's Chris Steak House", 'dinner', '16 oz', 1370, 80, 2, 114, 920, ['steak', 'ribeye']),
  item('rc-cowboy', 'Cowboy Ribeye (26 oz)', "Ruth's Chris Steak House", 'dinner', '26 oz', 3110, 148, 4, 276, 1480, ['steak', 'ribeye']),
  item('rc-tbone', 'T-Bone (24 oz)', "Ruth's Chris Steak House", 'dinner', '24 oz', 1220, 98, 2, 90, 1120, ['steak', 'tbone']),
  item('rc-porterhouse', 'Porterhouse (40 oz)', "Ruth's Chris Steak House", 'dinner', '40 oz', 2260, 168, 4, 174, 1680, ['steak']),
  item('rc-tomahawk', 'Tomahawk Ribeye (40 oz)', "Ruth's Chris Steak House", 'dinner', '40 oz', 3160, 152, 4, 280, 1820, ['steak', 'ribeye']),
  item('rc-lamb', 'Lamb Chops', "Ruth's Chris Steak House", 'dinner', '1 order', 860, 62, 4, 66, 980, ['lamb']),
  item('rc-pork', 'Pork Chop with Cinnamon Apples', "Ruth's Chris Steak House", 'dinner', '1 entrée', 820, 58, 28, 52, 1120, ['pork']),
  item('rc-stuffed-chicken', 'Stuffed Chicken Breast', "Ruth's Chris Steak House", 'dinner', '1 entrée', 740, 68, 8, 48, 1280, ['chicken']),
  item('rc-salmon-shrimp', 'Salmon & Shrimp', "Ruth's Chris Steak House", 'dinner', '1 entrée', 930, 72, 8, 66, 1420, ['salmon', 'shrimp']),
  item('rc-sea-bass', 'Garlic Crusted Sea Bass', "Ruth's Chris Steak House", 'dinner', '1 entrée', 770, 48, 22, 52, 980, ['fish']),
  item('rc-crab-cakes', 'Sizzling Crab Cakes', "Ruth's Chris Steak House", 'snacks', '2 cakes', 320, 22, 8, 22, 780, ['crab']),
  item('rc-calamari', 'Calamari', "Ruth's Chris Steak House", 'snacks', '1 order', 990, 36, 68, 62, 1680, ['calamari']),
  item('rc-creamed-spinach', 'Creamed Spinach', "Ruth's Chris Steak House", 'snacks', '1 side', 440, 12, 18, 36, 880, ['side']),
  item('rc-mashed', 'Garlic Mashed Potatoes', "Ruth's Chris Steak House", 'snacks', '1 side', 440, 8, 42, 28, 720, ['side']),
  item('rc-au-gratin', 'Au Gratin Potatoes', "Ruth's Chris Steak House", 'snacks', '1 side', 560, 16, 48, 34, 980, ['side']),
  item('rc-loaded-potato', 'Loaded Baked Potato', "Ruth's Chris Steak House", 'snacks', '1 potato', 930, 22, 72, 58, 1280, ['side']),
  item('rc-lobster-mac', 'Lobster Mac & Cheese', "Ruth's Chris Steak House", 'snacks', '1 side', 930, 38, 62, 58, 1480, ['mac', 'lobster']),
  item('rc-chop-salad', "Ruth's Chop Salad", "Ruth's Chris Steak House", 'lunch', '1 salad', 470, 22, 28, 32, 980, ['salad']),
  item('rc-caesar', 'Caesar Salad', "Ruth's Chris Steak House", 'lunch', '1 salad', 500, 14, 22, 40, 920, ['salad']),

  // Fleming's Prime Steakhouse — March 2026 nutrition PDF
  item('fl-filet-11', 'Main Filet Mignon (11 oz)', "Fleming's Prime Steakhouse", 'dinner', '11 oz', 590, 74, 2, 32, 610, ['steak', 'filet']),
  item('fl-petite-filet', 'Petite Filet Mignon (8 oz)', "Fleming's Prime Steakhouse", 'dinner', '8 oz', 440, 54, 1, 25, 460, ['steak', 'filet']),
  item('fl-bone-in-filet', 'Bone-In Filet Mignon (14 oz)', "Fleming's Prime Steakhouse", 'dinner', '14 oz', 550, 74, 1, 26, 1030, ['steak', 'filet']),
  item('fl-ny-strip', 'Prime New York Strip (16 oz)', "Fleming's Prime Steakhouse", 'dinner', '16 oz', 1000, 84, 0, 74, 510, ['steak', 'strip']),
  item('fl-bone-in-ribeye', 'Prime Bone-In Ribeye (20 oz)', "Fleming's Prime Steakhouse", 'dinner', '20 oz', 1470, 92, 2, 122, 2210, ['steak', 'ribeye']),
  item('fl-petite-ribeye', 'Prime Petite Bone-In Ribeye (14 oz)', "Fleming's Prime Steakhouse", 'dinner', '14 oz', 1020, 61, 1, 86, 2080, ['steak', 'ribeye']),
  item('fl-dry-aged-ribeye', 'Prime Dry-Aged Ribeye (16 oz)', "Fleming's Prime Steakhouse", 'dinner', '16 oz', 1130, 72, 1, 93, 610, ['steak', 'ribeye']),
  item('fl-tomahawk', 'Prime Tomahawk (35 oz)', "Fleming's Prime Steakhouse", 'dinner', '35 oz', 2110, 108, 2, 186, 2680, ['steak', 'ribeye']),
  item('fl-bbq-salmon', 'Barbecue Salmon Fillet', "Fleming's Prime Steakhouse", 'dinner', '1 entrée', 540, 52, 12, 32, 530, ['salmon', 'fish']),
  item('fl-sea-bass', 'Miso Glazed Chilean Sea Bass', "Fleming's Prime Steakhouse", 'dinner', '1 entrée', 690, 31, 11, 59, 960, ['fish']),
  item('fl-chicken', 'Double Breast of Chicken', "Fleming's Prime Steakhouse", 'dinner', '1 entrée', 630, 102, 11, 18, 1440, ['chicken']),
  item('fl-pork', 'Double Bone-In Pork Chop (20 oz)', "Fleming's Prime Steakhouse", 'dinner', '20 oz', 1050, 92, 37, 56, 4200, ['pork']),
  item('fl-crab-cakes', 'Crab Cakes', "Fleming's Prime Steakhouse", 'snacks', '1 order', 460, 23, 10, 34, 1470, ['crab']),
  item('fl-calamari', 'Sweet Chili Calamari', "Fleming's Prime Steakhouse", 'snacks', '1 order', 870, 41, 88, 39, 1870, ['calamari']),
  item('fl-onion-rings', 'Signature Onion Rings', "Fleming's Prime Steakhouse", 'snacks', '1 order', 1340, 23, 103, 93, 1770, ['onion rings']),
  item('fl-shrimp-cocktail', 'Shrimp Cocktail', "Fleming's Prime Steakhouse", 'snacks', '1 order', 300, 39, 21, 6, 1260, ['shrimp']),
  item('fl-wedge', 'Wedge Salad with Dressing', "Fleming's Prime Steakhouse", 'lunch', '1 salad', 560, 18, 16, 50, 1020, ['salad']),
  item('fl-caesar', 'Caesar Salad with Dressing', "Fleming's Prime Steakhouse", 'lunch', '1 salad', 380, 20, 13, 29, 1370, ['salad']),
  item('fl-flemings-potatoes', "Fleming's Potatoes", "Fleming's Prime Steakhouse", 'snacks', '1 side', 880, 21, 67, 60, 1090, ['side']),
  item('fl-mashed', 'Mashed Potatoes', "Fleming's Prime Steakhouse", 'snacks', '1 side', 620, 6, 54, 42, 960, ['side']),
  item('fl-mac', 'Chipotle Cheddar Mac & Cheese', "Fleming's Prime Steakhouse", 'snacks', '1 side', 1270, 32, 89, 87, 1750, ['mac', 'side']),
  item('fl-cheesecake', 'New York Cheesecake', "Fleming's Prime Steakhouse", 'snacks', '1 dessert', 1110, 18, 101, 69, 850, ['dessert']),
  item('fl-creme-brulee', 'Crème Brûlée', "Fleming's Prime Steakhouse", 'snacks', '1 dessert', 750, 6, 41, 63, 60, ['dessert']),

  // The Capital Grille — nutrition guide valid 8/24/26
  item('tcg-filet-8', 'Filet Mignon (8 oz)', 'The Capital Grille', 'dinner', '8 oz', 390, 43, 2, 23, 400, ['steak', 'filet']),
  item('tcg-filet-10', 'Filet Mignon (10 oz)', 'The Capital Grille', 'dinner', '10 oz', 490, 54, 3, 29, 500, ['steak', 'filet']),
  item('tcg-bone-in-ribeye', 'Bone-In Ribeye (22 oz)', 'The Capital Grille', 'dinner', '22 oz', 990, 80, 4, 72, 1060, ['steak', 'ribeye']),
  item('tcg-dry-aged-strip-14', 'Dry Aged NY Strip (14 oz)', 'The Capital Grille', 'dinner', '14 oz', 710, 83, 0, 42, 630, ['steak', 'strip']),
  item('tcg-dry-aged-strip-18', 'Dry Aged Bone-In NY Strip (18 oz)', 'The Capital Grille', 'dinner', '18 oz', 830, 98, 0, 49, 740, ['steak', 'strip']),
  item('tcg-porterhouse', 'Dry Aged Porterhouse (24 oz)', 'The Capital Grille', 'dinner', '24 oz', 960, 99, 4, 61, 450, ['steak']),
  item('tcg-porcini-ribeye', 'Porcini Rubbed Bone-In Ribeye', 'The Capital Grille', 'dinner', '1 entrée', 990, 80, 5, 72, 1060, ['steak', 'ribeye']),
  item('tcg-kona-strip', 'Kona-Crusted Dry Aged Bone-In NY Strip', 'The Capital Grille', 'dinner', '1 entrée', 950, 85, 9, 65, 1030, ['steak', 'strip']),
  item('tcg-au-poivre', 'Dry Aged Strip au Poivre', 'The Capital Grille', 'dinner', '1 entrée', 730, 85, 5, 41, 510, ['steak', 'strip']),
  item('tcg-gorgonzola-strip', 'Gorgonzola-Crusted Dry Aged Bone-In NY Strip', 'The Capital Grille', 'dinner', '1 entrée', 1100, 110, 12, 68, 1420, ['steak', 'strip']),
  item('tcg-cheeseburger', "The Grille's Signature Cheeseburger", 'The Capital Grille', 'sandwiches', '1 burger', 1040, 52, 51, 70, 1390, ['burger']),
  item('tcg-ribeye-sandwich', 'Ribeye Steak Sandwich', 'The Capital Grille', 'sandwiches', '1 sandwich', 1180, 91, 71, 59, 1270, ['sandwich', 'steak']),
  item('tcg-cobb', 'Cobb Salad with Sliced Tenderloin', 'The Capital Grille', 'lunch', '1 salad', 680, 43, 21, 49, 1200, ['salad', 'steak']),
  item('tcg-caesar', 'Caesar Salad with Grana Padano Croutons', 'The Capital Grille', 'lunch', '1 salad', 420, 13, 29, 27, 690, ['salad']),
  item('tcg-wedge', 'Wedge Salad with Gorgonzola & Candied Bacon', 'The Capital Grille', 'lunch', '1 salad', 710, 18, 36, 56, 1230, ['salad']),
  item('tcg-salmon', 'Seared Citrus-Glazed Salmon', 'The Capital Grille', 'dinner', '1 entrée', 720, 50, 25, 48, 480, ['salmon', 'fish']),
  item('tcg-sea-bass', 'Seared Sea Bass with Miso Butter', 'The Capital Grille', 'dinner', '1 entrée', 830, 50, 6, 66, 660, ['fish']),
  item('tcg-chicken', 'Roasted Chicken Breast with Fingerling Potatoes', 'The Capital Grille', 'dinner', '1 entrée', 880, 78, 34, 49, 1750, ['chicken']),
  item('tcg-calamari', 'Pan-Fried Calamari with Hot Cherry Peppers', 'The Capital Grille', 'snacks', '1 serving (of 2)', 710, 17, 36, 56, 1780, ['calamari']),
  item('tcg-shrimp-cocktail', 'Shrimp Cocktail (5)', 'The Capital Grille', 'snacks', '5 shrimp', 170, 26, 16, 0.5, 1460, ['shrimp']),
  item('tcg-mashed', "Sam's Mashed Potatoes (per serving)", 'The Capital Grille', 'snacks', '1 serving', 460, 5, 31, 36, 960, ['side']),
  item('tcg-creamed-spinach', 'Creamed Spinach (per serving)', 'The Capital Grille', 'snacks', '1 serving', 400, 10, 16, 35, 980, ['side']),
  item('tcg-au-gratin', 'Au Gratin Potatoes (per serving)', 'The Capital Grille', 'snacks', '1 serving', 420, 15, 27, 28, 1050, ['side']),
  item('tcg-lobster-mac', "Lobster Mac 'N' Cheese (per serving)", 'The Capital Grille', 'snacks', '1 serving', 830, 25, 56, 57, 1130, ['mac', 'lobster']),
  item('tcg-cheesecake', 'The Capital Grille Cheesecake', 'The Capital Grille', 'snacks', '1 dessert', 1060, 15, 110, 62, 650, ['dessert']),
  item('tcg-creme-brulee', 'Classic Crème Brûlée', 'The Capital Grille', 'snacks', '1 dessert', 470, 4, 33, 36, 80, ['dessert']),
];
