import type { FastFoodCategory, FastFoodItem } from './fastFoodMenu';

/**
 * Third wave of missing popular places (Florida + Southeast / national).
 * Just Salad — Jul 2026 nutrition guide (macros; salads exclude dressing).
 * Nature's Table — 2024 nutrition PDF (full macros).
 * Duffy's Sports Grill — published nutritional guide (full macros).
 * Mission BBQ — Aug 2025 nutrition PDF (full macros).
 * Newk's Eatery — Nutritionix portal (full macros).
 * Hooters — Sep 2023 master nutrition PDF (wings without sauce/dressing).
 * TooJay's — menu calories + 2019 nutritionals; macros Atwater-aligned where PDF incomplete.
 */
const item = (
  id: string,
  name: string,
  restaurant: string,
  category: FastFoodCategory,
  serving: string,
  calories: number,
  protein: number,
  carbs: number,
  fat: number,
  sodium: number,
  keywords?: string[],
): FastFoodItem => ({ id, name, restaurant, category, serving, calories, protein, carbs, fat, sodium, ...(keywords ? { keywords } : {}) });

export const CASUAL_LOCALS_FAST_FOOD_ITEMS: FastFoodItem[] = [
  // ——— Just Salad (Jul 2026 nutrition guide; salads without dressing) ———
  item('js-crispy-poblano', 'Crispy Chicken Poblano', 'Just Salad', 'lunch', '1 salad', 530, 21, 47, 32, 890, ['salad', 'chicken']),
  item('js-tokyo-chicken', 'Tokyo Supergreens with Chicken', 'Just Salad', 'lunch', '1 salad', 350, 32, 21, 17, 500, ['salad', 'chicken']),
  item('js-tokyo-tofu', 'Tokyo Supergreens with Tofu', 'Just Salad', 'lunch', '1 salad', 320, 18, 23, 20, 340, ['salad', 'tofu', 'vegan']),
  item('js-thai-crunch', 'Thai Chicken Crunch', 'Just Salad', 'lunch', '1 salad', 310, 28, 29, 9, 570, ['salad', 'chicken']),
  item('js-chicken-caesar', 'Chicken Caesar', 'Just Salad', 'lunch', '1 salad', 400, 37, 23, 18, 940, ['salad', 'caesar']),
  item('js-buffalo-chicken', 'Buffalo Chicken Salad', 'Just Salad', 'lunch', '1 salad', 460, 37, 18, 28, 840, ['salad', 'buffalo']),
  item('js-balsamic-avocado', 'Balsamic Chicken Avocado', 'Just Salad', 'lunch', '1 salad', 380, 33, 22, 19, 430, ['salad', 'avocado']),
  item('js-earth-bowl', 'Earth Bowl', 'Just Salad', 'lunch', '1 bowl', 600, 22, 60, 33, 920, ['bowl', 'vegetarian']),
  item('js-earth-chicken', 'Earth Bowl with Chicken', 'Just Salad', 'lunch', '1 bowl', 740, 44, 60, 38, 1250, ['bowl', 'chicken']),
  item('js-cilantro-lime', 'Cilantro Lime Chicken Bowl', 'Just Salad', 'lunch', '1 bowl', 830, 48, 82, 37, 1390, ['bowl', 'chicken']),
  item('js-peruvian', 'Peruvian Chicken Bowl', 'Just Salad', 'lunch', '1 bowl', 920, 43, 105, 39, 1360, ['bowl', 'chicken']),
  // Hero Wrap™ carbs include ~33–39g fiber; store net carbs so Atwater matches published kcal
  item('js-honey-crispy-wrap', 'Honey Crispy Chicken Wrap', 'Just Salad', 'sandwiches', '1 wrap', 660, 37, 42, 38, 1530, ['wrap', 'chicken']),
  item('js-spicy-caesar-wrap', 'Spicy Chicken Caesar Wrap', 'Just Salad', 'sandwiches', '1 wrap', 560, 51, 24, 29, 1560, ['wrap', 'caesar']),
  item('js-buffalo-wrap', 'Buffalo Chicken Wrap', 'Just Salad', 'sandwiches', '1 wrap', 600, 50, 12, 39, 1460, ['wrap', 'buffalo']),
  item('js-acai-smoothie', 'Açaí Protein Punch Smoothie', 'Just Salad', 'snacks', '1 smoothie', 520, 27, 69, 19, 170, ['smoothie', 'acai']),
  item('js-pb-smoothie', 'PB Protein Smoothie', 'Just Salad', 'snacks', '1 smoothie', 460, 32, 63, 12, 240, ['smoothie']),
  item('js-chicken-noodle', 'Chicken Noodle Soup (large)', 'Just Salad', 'lunch', '1 large', 220, 16, 22, 6, 1440, ['soup']),
  item('js-broccoli-cheddar', 'Broccoli Cheddar Soup (large)', 'Just Salad', 'lunch', '1 large', 460, 18, 28, 32, 1600, ['soup']),

  // ——— Nature's Table (2024 nutrition PDF) ———
  item('nt-sesame-thai-wrap', 'Sesame Thai Wrap', "Nature's Table", 'sandwiches', '1 wrap', 717, 39, 73, 31, 679, ['wrap']),
  item('nt-chipotle-wrap', 'Chipotle Chicken Wrap', "Nature's Table", 'sandwiches', '1 wrap', 785, 44, 74, 34, 1166, ['wrap', 'chicken']),
  item('nt-caesar-wrap', 'Chicken Caesar Wrap', "Nature's Table", 'sandwiches', '1 wrap', 709, 48, 56, 33, 1449, ['wrap', 'caesar']),
  item('nt-buffalo-wrap', 'Spicy Buffalo Chicken Wrap', "Nature's Table", 'sandwiches', '1 wrap', 567, 42, 52, 25, 855, ['wrap', 'buffalo']),
  item('nt-baja-turkey', 'Baja Turkey Jack (toasted)', "Nature's Table", 'sandwiches', '1 sandwich', 756, 44, 63, 38, 1881, ['turkey']),
  item('nt-turkey-club', 'Turkey Club (toasted)', "Nature's Table", 'sandwiches', '1 sandwich', 645, 49, 76, 17, 1848, ['turkey', 'club']),
  item('nt-bbq-pork', 'BBQ Pork & Slaw (toasted)', "Nature's Table", 'sandwiches', '1 sandwich', 759, 37, 79, 34, 2119, ['bbq', 'pork']),
  item('nt-california-club', 'California Club', "Nature's Table", 'sandwiches', '1 sandwich', 650, 44, 68, 21, 1465, ['club']),
  item('nt-chicken-salad-sand', 'Chicken Salad Sandwich', "Nature's Table", 'sandwiches', '1 sandwich', 565, 26, 72, 19, 787, ['chicken salad']),
  item('nt-tuna', 'Tuna Salad Sandwich', "Nature's Table", 'sandwiches', '1 sandwich', 740, 46, 70, 30, 874, ['tuna']),
  item('nt-chipotle-bowl', 'Chipotle Protein Bowl', "Nature's Table", 'lunch', '1 bowl', 683, 42, 66, 28, 715, ['bowl']),
  item('nt-latin-bowl', 'Latin Citrus Protein Bowl', "Nature's Table", 'lunch', '1 bowl', 551, 39, 82, 8, 606, ['bowl']),
  item('nt-med-salad', 'Mediterranean Chicken Salad', "Nature's Table", 'lunch', '1 salad', 390, 32, 13, 24, 957, ['salad']),
  item('nt-caesar-salad', 'Chicken Caesar Salad', "Nature's Table", 'lunch', '1 salad', 434, 38, 20, 24, 867, ['salad', 'caesar']),
  item('nt-siesta', 'Siesta Cooler Smoothie (22 oz)', "Nature's Table", 'snacks', '22 oz', 177, 1, 44, 2, 31, ['smoothie']),
  item('nt-hawaiian', 'Hawaiian Crush Smoothie (22 oz)', "Nature's Table", 'snacks', '22 oz', 237, 1, 54, 3, 34, ['smoothie']),
  item('nt-pb-cup', 'Peanut Butter Cup Smoothie (22 oz)', "Nature's Table", 'snacks', '22 oz', 832, 20, 128, 29, 525, ['smoothie']),
  item('nt-acai', 'Traditional Acai Bowl', "Nature's Table", 'breakfast', '1 bowl', 338, 3, 65, 10, 56, ['acai', 'bowl']),
  item('nt-breakfast-burrito', 'Classic Breakfast Burrito', "Nature's Table", 'breakfast', '1 burrito', 614, 31, 57, 29, 1347, ['breakfast', 'burrito']),
  item('nt-avocado-toast', 'Avocado Toast', "Nature's Table", 'breakfast', '1 order', 294, 8, 39, 13, 310, ['avocado', 'toast']),

  // ——— Duffy's Sports Grill (nutrition guide) ———
  item('duffy-cheeseburger', "Duffy's Cheeseburger", "Duffy's Sports Grill", 'sandwiches', '1 burger', 930, 45, 50, 58, 3480, ['burger']),
  item('duffy-bacon-mushroom', 'Bacon Mushroom Cheeseburger', "Duffy's Sports Grill", 'sandwiches', '1 burger', 1250, 61, 56, 86, 4480, ['burger']),
  item('duffy-blazin', "Blazin' BBQ Cheeseburger", "Duffy's Sports Grill", 'sandwiches', '1 burger', 1550, 65, 99, 98, 3830, ['burger', 'bbq']),
  item('duffy-turkey-burger', 'Grilled Turkey Burger', "Duffy's Sports Grill", 'sandwiches', '1 burger', 570, 48, 45, 22, 1670, ['burger', 'turkey']),
  item('duffy-black-bean', 'Black Bean Veggie Burger', "Duffy's Sports Grill", 'sandwiches', '1 burger', 790, 19, 85, 44, 2300, ['burger', 'vegetarian']),
  item('duffy-buffalo-crispy', 'Buffalo Chicken Sandwich (crispy)', "Duffy's Sports Grill", 'sandwiches', '1 sandwich', 790, 59, 53, 39, 750, ['chicken', 'buffalo']),
  item('duffy-reuben', 'New York Reuben', "Duffy's Sports Grill", 'sandwiches', '1 sandwich', 960, 50, 65, 58, 4780, ['reuben']),
  item('duffy-philly', 'Philadelphia Cheese Steak (ribeye)', "Duffy's Sports Grill", 'sandwiches', '1 sandwich', 970, 53, 64, 57, 2180, ['philly']),
  item('duffy-wings-breaded', 'Traditional Breaded Wings (10)', "Duffy's Sports Grill", 'dinner', '10 wings', 1190, 64, 12, 100, 660, ['wings']),
  item('duffy-wings-boneless', 'Boneless Wings (10)', "Duffy's Sports Grill", 'dinner', '10 wings', 940, 81, 12, 63, 520, ['wings', 'boneless']),
  item('duffy-tenders', 'Buttermilk Chicken Tenders', "Duffy's Sports Grill", 'dinner', '1 order', 870, 62, 28, 57, 790, ['tenders']),
  item('duffy-jerk', 'Caribbean Jerk Chicken', "Duffy's Sports Grill", 'dinner', '1 entrée', 480, 46, 42, 15, 1240, ['chicken', 'jerk']),
  item('duffy-sirloin', 'Center-Cut Top Sirloin (8 oz)', "Duffy's Sports Grill", 'dinner', '8 oz', 650, 69, 13, 34, 2690, ['steak']),
  item('duffy-ny-strip', 'New York Strip Steak (11 oz)', "Duffy's Sports Grill", 'dinner', '11 oz', 890, 66, 10, 62, 1400, ['steak']),
  item('duffy-salmon', 'Wild Alaska Salmon', "Duffy's Sports Grill", 'dinner', '1 entrée', 390, 49, 6, 18, 350, ['salmon', 'seafood']),
  item('duffy-mahi', 'Mahi Mahi', "Duffy's Sports Grill", 'dinner', '1 entrée', 260, 43, 6, 7, 290, ['mahi', 'seafood']),
  item('duffy-scampi', 'Shrimp Scampi', "Duffy's Sports Grill", 'dinner', '1 entrée', 1720, 42, 105, 127, 2620, ['shrimp', 'pasta']),
  item('duffy-alfredo', 'Fettuccine Alfredo with Chicken', "Duffy's Sports Grill", 'dinner', '1 entrée', 1960, 70, 108, 131, 2150, ['pasta', 'chicken']),
  item('duffy-cobb', 'Cobb Salad with Chicken', "Duffy's Sports Grill", 'lunch', '1 salad', 560, 58, 12, 33, 1100, ['salad', 'cobb']),
  item('duffy-caesar', 'Caesar Salad with Chicken', "Duffy's Sports Grill", 'lunch', '1 salad', 970, 68, 53, 57, 1940, ['salad', 'caesar']),

  // ——— Mission BBQ (Aug 2025 nutrition PDF) ———
  item('mbq-brisket-moist', 'Brisket Sandwich (moist, 6 oz)', 'Mission BBQ', 'sandwiches', '1 sandwich', 566, 34, 24, 36, 1125, ['brisket', 'bbq']),
  item('mbq-brisket-lean', 'Brisket Sandwich (lean, 6 oz)', 'Mission BBQ', 'sandwiches', '1 sandwich', 480, 59, 24, 15, 1100, ['brisket', 'bbq']),
  item('mbq-chopped-brisket', 'Chopped Brisket Sandwich', 'Mission BBQ', 'sandwiches', '1 sandwich', 591, 40, 47, 24, 1357, ['brisket', 'bbq']),
  item('mbq-pulled-pork', 'Pulled Pork Sandwich', 'Mission BBQ', 'sandwiches', '1 sandwich', 572, 47, 22, 31, 648, ['pork', 'bbq']),
  item('mbq-turkey', 'Turkey Sandwich', 'Mission BBQ', 'sandwiches', '1 sandwich', 418, 52, 23, 12, 412, ['turkey', 'bbq']),
  item('mbq-pulled-chicken', 'Pulled Chicken Sandwich', 'Mission BBQ', 'sandwiches', '1 sandwich', 423, 44, 24, 15, 1182, ['chicken', 'bbq']),
  item('mbq-brisket-burger', 'Brisket Burger', 'Mission BBQ', 'sandwiches', '1 burger', 724, 86, 22, 30, 762, ['burger', 'brisket']),
  item('mbq-smoked-burger', 'Smoked Cheeseburger', 'Mission BBQ', 'sandwiches', '1 burger', 679, 49, 41, 33, 989, ['burger']),
  item('mbq-ribs-5', 'Bay-B-Back Ribs (5 bone)', 'Mission BBQ', 'dinner', '5 bones', 990, 77, 3, 72, 887, ['ribs', 'bbq']),
  item('mbq-pulled-pork-meat', 'Pulled Pork (meat market)', 'Mission BBQ', 'dinner', '1 portion', 603, 57, 0, 40, 577, ['pork', 'bbq']),
  item('mbq-turkey-meat', 'Turkey (meat market, 8 oz)', 'Mission BBQ', 'dinner', '8 oz', 398, 64, 2, 13, 263, ['turkey', 'bbq']),
  item('mbq-chicken', 'Half Chicken', 'Mission BBQ', 'dinner', '1 half', 613, 85, 0, 30, 942, ['chicken', 'bbq']),
  item('mbq-mac', "Maggie's Mac-N-Cheese", 'Mission BBQ', 'snacks', '1 side', 304, 15, 17, 20, 998, ['mac', 'side']),
  item('mbq-fries', 'Fresh Cut Fries', 'Mission BBQ', 'snacks', '1 side', 377, 5, 40, 29, 419, ['fries', 'side']),
  item('mbq-beans', 'Baked Beans with Brisket', 'Mission BBQ', 'snacks', '1 side', 199, 9, 35, 2, 670, ['beans', 'side']),
  item('mbq-cornbread', 'Cornbread', 'Mission BBQ', 'snacks', '1 piece', 205, 4, 29, 9, 228, ['cornbread', 'side']),

  // ——— Newk's Eatery (Nutritionix portal) ———
  item('newk-q-sandwich', 'Newk\'s "Q" Sandwich', "Newk's Eatery", 'sandwiches', '1 sandwich', 1080, 56, 78, 58, 2100, ['bbq']),
  item('newk-club', "Newk's Club Sandwich", "Newk's Eatery", 'sandwiches', '1 sandwich', 880, 46, 88, 35, 2550, ['club']),
  item('newk-italian', 'The Italian Sandwich', "Newk's Eatery", 'sandwiches', '1 sandwich', 1170, 38, 76, 70, 3860, ['italian']),
  item('newk-pesto-chicken', 'Pesto Chicken Sandwich', "Newk's Eatery", 'sandwiches', '1 sandwich', 830, 56, 77, 31, 1440, ['chicken', 'pesto']),
  item('newk-chicken-salad', 'Chicken Salad Sandwich', "Newk's Eatery", 'sandwiches', '1 sandwich', 940, 43, 75, 51, 1690, ['chicken salad']),
  item('newk-turkey-avocado', 'Turkey Avocado Sandwich', "Newk's Eatery", 'sandwiches', '1 sandwich', 790, 44, 84, 28, 2030, ['turkey', 'avocado']),
  item('newk-ultimate-salad', 'Ultimate Salad', "Newk's Eatery", 'lunch', '1 salad', 660, 64, 23, 32, 1710, ['salad']),
  item('newk-favorite-salad', "Newk's Favorite Salad", "Newk's Eatery", 'lunch', '1 salad', 740, 43, 62, 33, 970, ['salad']),
  item('newk-cobb', 'Cobb Salad', "Newk's Eatery", 'lunch', '1 salad', 910, 55, 44, 54, 1240, ['salad', 'cobb']),
  item('newk-southern', 'Southern Salad', "Newk's Eatery", 'lunch', '1 salad', 560, 27, 22, 41, 690, ['salad']),
  item('newk-q-pizza', 'Newk\'s "Q" Pizza', "Newk's Eatery", 'dinner', '1 pizza', 1110, 55, 52, 72, 3360, ['pizza', 'bbq']),
  item('newk-pepperoni', 'Pepperoni Pizza', "Newk's Eatery", 'dinner', '1 pizza', 730, 36, 50, 39, 1960, ['pizza']),
  item('newk-margherita', 'Margherita Pizza', "Newk's Eatery", 'dinner', '1 pizza', 510, 25, 52, 21, 1310, ['pizza']),
  item('newk-mac', 'Five Cheese Mac & Cheese', "Newk's Eatery", 'lunch', '1 order', 790, 28, 55, 49, 1990, ['mac']),
  item('newk-tomato-soup', 'Tomato Basil Soup', "Newk's Eatery", 'lunch', '1 bowl', 580, 8, 40, 43, 2290, ['soup']),
  item('newk-caesar-wrap', 'Chicken Caesar Wrap', "Newk's Eatery", 'sandwiches', '1 wrap', 820, 30, 52, 55, 1510, ['wrap', 'caesar']),

  // ——— Hooters (Sep 2023 nutrition PDF; wings plain) ———
  item('hoot-original-10', 'Original Wings (10, no sauce)', 'Hooters', 'dinner', '10 wings', 950, 75, 24, 57, 380, ['wings']),
  item('hoot-daytona-10', 'Daytona Beach Style Wings (10)', 'Hooters', 'dinner', '10 wings', 820, 88, 25, 43, 1440, ['wings']),
  item('hoot-naked-10', 'Naked Wings (10, no sauce)', 'Hooters', 'dinner', '10 wings', 720, 88, 1, 43, 320, ['wings']),
  item('hoot-boneless-10', 'Boneless Wings (10, no sauce)', 'Hooters', 'dinner', '10 wings', 730, 68, 40, 33, 1530, ['wings', 'boneless']),
  item('hoot-tenders-5', 'Chicken Tenders (5)', 'Hooters', 'dinner', '5 tenders', 700, 77, 25, 33, 1800, ['tenders']),
  item('hoot-buffalo-sand-fried', 'Buffalo Chicken Sandwich (fried)', 'Hooters', 'sandwiches', '1 sandwich', 670, 40, 68, 27, 1030, ['chicken', 'buffalo']),
  item('hoot-buffalo-sand-grilled', 'Buffalo Chicken Sandwich (grilled)', 'Hooters', 'sandwiches', '1 sandwich', 560, 59, 43, 18, 3890, ['chicken', 'buffalo']),
  item('hoot-tender-melt', 'Chicken Tender Melt Sandwich', 'Hooters', 'sandwiches', '1 sandwich', 1020, 80, 64, 50, 2250, ['chicken']),
  item('hoot-texas-melt', 'Twisted Texas Melt', 'Hooters', 'sandwiches', '1 burger', 1020, 41, 61, 69, 3920, ['burger']),
  item('hoot-western-bbq', 'Western BBQ Burger', 'Hooters', 'sandwiches', '1 burger', 1050, 46, 59, 70, 3820, ['burger', 'bbq']),
  item('hoot-curly-fries', 'Curly Fries', 'Hooters', 'snacks', '1 side', 500, 7, 62, 24, 460, ['fries']),
  item('hoot-tots', 'Tots', 'Hooters', 'snacks', '1 side', 500, 6, 56, 28, 880, ['tots']),

  // ——— TooJay's (menu calories + 2019 nutritionals; macros estimated where needed) ———
  item('tj-reuben', 'Reuben', "TooJay's", 'sandwiches', '1 sandwich + sides', 1520, 62, 98, 88, 3280, ['reuben', 'corned beef']),
  item('tj-rachel', 'Rachel', "TooJay's", 'sandwiches', '1 sandwich + sides', 1680, 64, 98, 102, 3180, ['pastrami', 'reuben']),
  item('tj-turkey-reuben', 'Turkey Reuben', "TooJay's", 'sandwiches', '1 sandwich + sides', 1470, 58, 98, 84, 3120, ['turkey', 'reuben']),
  item('tj-hot-pastrami', 'Hot Pastrami (mid-range)', "TooJay's", 'sandwiches', '1 sandwich', 755, 32, 49, 39, 2340, ['pastrami']),
  item('tj-hot-corned', 'Hot Corned Beef (mid-range)', "TooJay's", 'sandwiches', '1 sandwich', 605, 34, 49, 22, 3480, ['corned beef']),
  item('tj-turkey', 'Turkey Breast (mid-range)', "TooJay's", 'sandwiches', '1 sandwich', 550, 34, 52, 15, 3340, ['turkey']),
  item('tj-brisket-dip', 'Beef Brisket Dip', "TooJay's", 'sandwiches', '1 sandwich + sides', 1370, 58, 98, 72, 2980, ['brisket']),
  item('tj-triple-j', 'Triple J (mid-range)', "TooJay's", 'sandwiches', '1 sandwich', 960, 48, 62, 48, 2680, ['deli']),
  item('tj-classic', "TooJay's Classic (mid-range)", "TooJay's", 'sandwiches', '1 sandwich', 710, 38, 48, 36, 2480, ['deli']),
  item('tj-burger', "Burger ála TooJay's", "TooJay's", 'sandwiches', '1 burger + sides', 1510, 62, 98, 88, 2680, ['burger']),
  item('tj-chipotle-burger', 'Chipotle Bacon Burger', "TooJay's", 'sandwiches', '1 burger + sides', 1630, 64, 98, 98, 2780, ['burger']),
  item('tj-dill-chicken', 'Dill Chicken Salad Sandwich (mid)', "TooJay's", 'sandwiches', '1 sandwich', 780, 44, 54, 42, 2220, ['chicken salad']),
  item('tj-matzo', 'Matzo Ball Soup (bowl)', "TooJay's", 'lunch', '1 bowl', 880, 19, 48, 65, 1220, ['soup', 'matzo']),
  item('tj-chicken-noodle', 'Chicken Noodle Soup (bowl)', "TooJay's", 'lunch', '1 bowl', 100, 10, 12, 2, 160, ['soup']),
  item('tj-cobb', "TooJay's Cobb Salad", "TooJay's", 'lunch', '1 salad', 620, 51, 21, 32, 1220, ['salad', 'cobb']),
  item('tj-chopped', "TooJay's Chopped Salad", "TooJay's", 'lunch', '1 salad', 450, 29, 23, 25, 1840, ['salad']),
  item('tj-french-toast', 'French Toast (Challah)', "TooJay's", 'breakfast', '1 order', 1230, 28, 148, 52, 1180, ['french toast']),
  item('tj-waffle', 'Belgian Waffle', "TooJay's", 'breakfast', '1 waffle', 730, 14, 98, 28, 880, ['waffle']),
  item('tj-nova-bagel', 'Nova on a Bagel (mid-range)', "TooJay's", 'breakfast', '1 bagel', 760, 37, 98, 23, 1070, ['nova', 'bagel', 'lox']),
  item('tj-knish', "TooJay's Famous Potato Knish", "TooJay's", 'snacks', '1 knish', 360, 9, 50, 13, 570, ['knish']),
];
