/**
 * PDF Export Button Component
 * Generates and downloads PDF reports using jsPDF
 */

import React from 'react';
import { Button } from '@/components/ui/button';
import { Download, FileText } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import jsPDF from 'jspdf';

interface PDFExportButtonProps {
  nutritionData?: {
    dailyCalories: number;
    goalCalories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
  weeklyData?: any[];
  reportType?: 'daily' | 'weekly' | 'full';
  className?: string;
}

export function PDFExportButton({ 
  nutritionData, 
  weeklyData = [], 
  reportType = 'daily',
  className 
}: PDFExportButtonProps) {
  const { toast } = useToast();

  const generatePDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.width;
      const margin = 20;
      let yPosition = margin;

      // Header with ByteWise Logo (text-based)
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 165, 0); // Orange color
      doc.text('ByteWise', margin, yPosition);
      yPosition += 10;
      
      doc.setFontSize(12);
      doc.setTextColor(100, 100, 100);
      doc.text('Smart Nutrition Tracking', margin, yPosition);
      yPosition += 20;

      // Report Title
      doc.setFontSize(18);
      doc.setTextColor(0, 0, 0);
      doc.setFont('helvetica', 'bold');
      const reportTitle = reportType === 'daily' ? 'Daily Nutrition Report' : 
                         reportType === 'weekly' ? 'Weekly Nutrition Report' : 
                         'Comprehensive Nutrition Report';
      doc.text(reportTitle, margin, yPosition);
      yPosition += 15;

      // Date
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on: ${new Date().toLocaleDateString()}`, margin, yPosition);
      yPosition += 20;

      // Nutrition Summary
      if (nutritionData) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(0, 0, 0);
        doc.text('Nutrition Summary', margin, yPosition);
        yPosition += 15;

        const progress = Math.round((nutritionData.dailyCalories / nutritionData.goalCalories) * 100);
        
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');
        doc.text(`Daily Calories: ${nutritionData.dailyCalories} / ${nutritionData.goalCalories} (${progress}%)`, margin, yPosition);
        yPosition += 8;
        doc.text(`Protein: ${nutritionData.protein}g`, margin, yPosition);
        yPosition += 8;
        doc.text(`Carbohydrates: ${nutritionData.carbs}g`, margin, yPosition);
        yPosition += 8;
        doc.text(`Fat: ${nutritionData.fat}g`, margin, yPosition);
        yPosition += 20;
      }

      // Weekly Data
      if (weeklyData.length > 0 && reportType !== 'daily') {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Weekly Tracking Data', margin, yPosition);
        yPosition += 15;

        weeklyData.slice(0, 10).forEach((entry, index) => {
          if (yPosition > 250) { // Check if we need a new page
            doc.addPage();
            yPosition = margin;
          }
          
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          doc.text(`${entry.date}: ${entry.name} - ${entry.calories} cal`, margin, yPosition);
          yPosition += 6;
        });
      }

      // Footer
      const footerY = doc.internal.pageSize.height - 20;
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by ByteWise Nutrition Tracker', margin, footerY);
      doc.text(`Page 1`, pageWidth - margin - 20, footerY);

      // Save the PDF
      const fileName = `bytewise-${reportType}-report-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);

      toast({
        title: "PDF Generated Successfully",
        description: `Your ${reportType} nutrition report has been downloaded.`,
      });

    } catch (error) {
      console.error('PDF generation error:', error);
      toast({
        title: "PDF Generation Failed",
        description: "There was an error generating your PDF report. Please try again.",
        variant: "destructive",
      });
    }
  };

  return (
    <Button 
      onClick={generatePDF} 
      variant="outline" 
      className={className}
    >
      <Download className="w-4 h-4 mr-2" />
      Export PDF
    </Button>
  );
}

export default PDFExportButton;